// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: wnms_event.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventList     []*EventMessage        `protobuf:"bytes,1,rep,name=eventList,proto3" json:"eventList,omitempty"`
	EventNum      int32                  `protobuf:"varint,2,opt,name=eventNum,proto3" json:"eventNum,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // message converted time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReport) Reset() {
	*x = EventReport{}
	mi := &file_wnms_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReport) ProtoMessage() {}

func (x *EventReport) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReport.ProtoReflect.Descriptor instead.
func (*EventReport) Descriptor() ([]byte, []int) {
	return file_wnms_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventReport) GetEventList() []*EventMessage {
	if x != nil {
		return x.EventList
	}
	return nil
}

func (x *EventReport) GetEventNum() int32 {
	if x != nil {
		return x.EventNum
	}
	return 0
}

func (x *EventReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type EventMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description GPB version
	// @since 3.5
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Event code
	// @since 3.5
	EventCode string `protobuf:"bytes,2,opt,name=eventCode,proto3" json:"eventCode,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Event type
	// @since 3.5
	EventType *string `protobuf:"bytes,3,opt,name=eventType,proto3,oneof" json:"eventType,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Event main category
	// @since 3.5
	MainCategory string `protobuf:"bytes,4,opt,name=mainCategory,proto3" json:"mainCategory,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Event sub category
	// @since 3.5
	SubCategory *string `protobuf:"bytes,5,opt,name=subCategory,proto3,oneof" json:"subCategory,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Domain UUID
	// @since 3.5
	DomainId *string `protobuf:"bytes,6,opt,name=domainId,proto3,oneof" json:"domainId,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Zone UUID. Unique zone ID (for example, b381206b-2e5d-43dc-b249-e36ffae9855c) assigned by the controller.
	// @since 3.5
	ZoneId *string `protobuf:"bytes,7,opt,name=zoneId,proto3,oneof" json:"zoneId,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description AP Group identifier
	// @since 3.5
	ApGroupId *string `protobuf:"bytes,8,opt,name=apGroupId,proto3,oneof" json:"apGroupId,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Access Point  MAC address
	// @since 3.5
	ApMac *string `protobuf:"bytes,9,opt,name=apMac,proto3,oneof" json:"apMac,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description UE/Client MAC address if the events are related to client
	// @since 3.5
	ClientMac *string `protobuf:"bytes,10,opt,name=clientMac,proto3,oneof" json:"clientMac,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Event timestamp (UTC time)
	// @since 3.5
	Timestamp uint64 `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Event severity
	// @since 3.5
	Severity string `protobuf:"bytes,13,opt,name=severity,proto3" json:"severity,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Reason for the event to occur.
	// @since 3.5
	Reason *string `protobuf:"bytes,14,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Domain name.
	// @since 3.5
	DomainName *string `protobuf:"bytes,15,opt,name=domainName,proto3,oneof" json:"domainName,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Zone name. Zone name assigned by the controller . The admin configures the Zone name via the contoller's user interface. The controller passes it to the AP.  AP retains the zone name.
	// @since 3.5
	ZoneName *string `protobuf:"bytes,16,opt,name=zoneName,proto3,oneof" json:"zoneName,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description AP Group name
	// @since 3.5
	ApGroupName *string `protobuf:"bytes,17,opt,name=apGroupName,proto3,oneof" json:"apGroupName,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description IPv4 address of the AP
	// @since 3.5
	ApIpAddress *string `protobuf:"bytes,18,opt,name=apIpAddress,proto3,oneof" json:"apIpAddress,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description IPv6 address of the AP
	// @since 3.5
	ApIpv6Address *string `protobuf:"bytes,19,opt,name=apIpv6Address,proto3,oneof" json:"apIpv6Address,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description description of the event
	// @since 3.5
	Description string `protobuf:"bytes,20,opt,name=description,proto3" json:"description,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description disconnectReason of the event
	// @since 3.5
	DisconnectReason *string `protobuf:"bytes,21,opt,name=disconnectReason,proto3,oneof" json:"disconnectReason,omitempty"`
	Vendor           string  `protobuf:"bytes,41,opt,name=vendor,proto3" json:"vendor,omitempty"`
	NetworkType      string  `protobuf:"bytes,42,opt,name=networkType,proto3" json:"networkType,omitempty"`
	RegionCode       string  `protobuf:"bytes,91,opt,name=regionCode,proto3" json:"regionCode,omitempty"`
	FactoryCode      string  `protobuf:"bytes,92,opt,name=factoryCode,proto3" json:"factoryCode,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_wnms_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_wnms_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EventMessage) GetEventCode() string {
	if x != nil {
		return x.EventCode
	}
	return ""
}

func (x *EventMessage) GetEventType() string {
	if x != nil && x.EventType != nil {
		return *x.EventType
	}
	return ""
}

func (x *EventMessage) GetMainCategory() string {
	if x != nil {
		return x.MainCategory
	}
	return ""
}

func (x *EventMessage) GetSubCategory() string {
	if x != nil && x.SubCategory != nil {
		return *x.SubCategory
	}
	return ""
}

func (x *EventMessage) GetDomainId() string {
	if x != nil && x.DomainId != nil {
		return *x.DomainId
	}
	return ""
}

func (x *EventMessage) GetZoneId() string {
	if x != nil && x.ZoneId != nil {
		return *x.ZoneId
	}
	return ""
}

func (x *EventMessage) GetApGroupId() string {
	if x != nil && x.ApGroupId != nil {
		return *x.ApGroupId
	}
	return ""
}

func (x *EventMessage) GetApMac() string {
	if x != nil && x.ApMac != nil {
		return *x.ApMac
	}
	return ""
}

func (x *EventMessage) GetClientMac() string {
	if x != nil && x.ClientMac != nil {
		return *x.ClientMac
	}
	return ""
}

func (x *EventMessage) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EventMessage) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *EventMessage) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *EventMessage) GetDomainName() string {
	if x != nil && x.DomainName != nil {
		return *x.DomainName
	}
	return ""
}

func (x *EventMessage) GetZoneName() string {
	if x != nil && x.ZoneName != nil {
		return *x.ZoneName
	}
	return ""
}

func (x *EventMessage) GetApGroupName() string {
	if x != nil && x.ApGroupName != nil {
		return *x.ApGroupName
	}
	return ""
}

func (x *EventMessage) GetApIpAddress() string {
	if x != nil && x.ApIpAddress != nil {
		return *x.ApIpAddress
	}
	return ""
}

func (x *EventMessage) GetApIpv6Address() string {
	if x != nil && x.ApIpv6Address != nil {
		return *x.ApIpv6Address
	}
	return ""
}

func (x *EventMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventMessage) GetDisconnectReason() string {
	if x != nil && x.DisconnectReason != nil {
		return *x.DisconnectReason
	}
	return ""
}

func (x *EventMessage) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *EventMessage) GetNetworkType() string {
	if x != nil {
		return x.NetworkType
	}
	return ""
}

func (x *EventMessage) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

func (x *EventMessage) GetFactoryCode() string {
	if x != nil {
		return x.FactoryCode
	}
	return ""
}

var File_wnms_event_proto protoreflect.FileDescriptor

const file_wnms_event_proto_rawDesc = "" +
	"\n" +
	"\x10wnms_event.proto\x12\x1fkr.connectlabs.wnms.proto.model\"\x94\x01\n" +
	"\vEventReport\x12K\n" +
	"\teventList\x18\x01 \x03(\v2-.kr.connectlabs.wnms.proto.model.EventMessageR\teventList\x12\x1a\n" +
	"\beventNum\x18\x02 \x01(\x05R\beventNum\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x82\b\n" +
	"\fEventMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1c\n" +
	"\teventCode\x18\x02 \x01(\tR\teventCode\x12!\n" +
	"\teventType\x18\x03 \x01(\tH\x00R\teventType\x88\x01\x01\x12\"\n" +
	"\fmainCategory\x18\x04 \x01(\tR\fmainCategory\x12%\n" +
	"\vsubCategory\x18\x05 \x01(\tH\x01R\vsubCategory\x88\x01\x01\x12\x1f\n" +
	"\bdomainId\x18\x06 \x01(\tH\x02R\bdomainId\x88\x01\x01\x12\x1b\n" +
	"\x06zoneId\x18\a \x01(\tH\x03R\x06zoneId\x88\x01\x01\x12!\n" +
	"\tapGroupId\x18\b \x01(\tH\x04R\tapGroupId\x88\x01\x01\x12\x19\n" +
	"\x05apMac\x18\t \x01(\tH\x05R\x05apMac\x88\x01\x01\x12!\n" +
	"\tclientMac\x18\n" +
	" \x01(\tH\x06R\tclientMac\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\x04R\ttimestamp\x12\x1a\n" +
	"\bseverity\x18\r \x01(\tR\bseverity\x12\x1b\n" +
	"\x06reason\x18\x0e \x01(\tH\aR\x06reason\x88\x01\x01\x12#\n" +
	"\n" +
	"domainName\x18\x0f \x01(\tH\bR\n" +
	"domainName\x88\x01\x01\x12\x1f\n" +
	"\bzoneName\x18\x10 \x01(\tH\tR\bzoneName\x88\x01\x01\x12%\n" +
	"\vapGroupName\x18\x11 \x01(\tH\n" +
	"R\vapGroupName\x88\x01\x01\x12%\n" +
	"\vapIpAddress\x18\x12 \x01(\tH\vR\vapIpAddress\x88\x01\x01\x12)\n" +
	"\rapIpv6Address\x18\x13 \x01(\tH\fR\rapIpv6Address\x88\x01\x01\x12 \n" +
	"\vdescription\x18\x14 \x01(\tR\vdescription\x12/\n" +
	"\x10disconnectReason\x18\x15 \x01(\tH\rR\x10disconnectReason\x88\x01\x01\x12\x16\n" +
	"\x06vendor\x18) \x01(\tR\x06vendor\x12 \n" +
	"\vnetworkType\x18* \x01(\tR\vnetworkType\x12\x1e\n" +
	"\n" +
	"regionCode\x18[ \x01(\tR\n" +
	"regionCode\x12 \n" +
	"\vfactoryCode\x18\\ \x01(\tR\vfactoryCodeB\f\n" +
	"\n" +
	"_eventTypeB\x0e\n" +
	"\f_subCategoryB\v\n" +
	"\t_domainIdB\t\n" +
	"\a_zoneIdB\f\n" +
	"\n" +
	"_apGroupIdB\b\n" +
	"\x06_apMacB\f\n" +
	"\n" +
	"_clientMacB\t\n" +
	"\a_reasonB\r\n" +
	"\v_domainNameB\v\n" +
	"\t_zoneNameB\x0e\n" +
	"\f_apGroupNameB\x0e\n" +
	"\f_apIpAddressB\x10\n" +
	"\x0e_apIpv6AddressB\x13\n" +
	"\x11_disconnectReasonB\n" +
	"Z\b../modelb\x06proto3"

var (
	file_wnms_event_proto_rawDescOnce sync.Once
	file_wnms_event_proto_rawDescData []byte
)

func file_wnms_event_proto_rawDescGZIP() []byte {
	file_wnms_event_proto_rawDescOnce.Do(func() {
		file_wnms_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wnms_event_proto_rawDesc), len(file_wnms_event_proto_rawDesc)))
	})
	return file_wnms_event_proto_rawDescData
}

var file_wnms_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wnms_event_proto_goTypes = []any{
	(*EventReport)(nil),  // 0: kr.connectlabs.wnms.proto.model.EventReport
	(*EventMessage)(nil), // 1: kr.connectlabs.wnms.proto.model.EventMessage
}
var file_wnms_event_proto_depIdxs = []int32{
	1, // 0: kr.connectlabs.wnms.proto.model.EventReport.eventList:type_name -> kr.connectlabs.wnms.proto.model.EventMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wnms_event_proto_init() }
func file_wnms_event_proto_init() {
	if File_wnms_event_proto != nil {
		return
	}
	file_wnms_event_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wnms_event_proto_rawDesc), len(file_wnms_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wnms_event_proto_goTypes,
		DependencyIndexes: file_wnms_event_proto_depIdxs,
		MessageInfos:      file_wnms_event_proto_msgTypes,
	}.Build()
	File_wnms_event_proto = out.File
	file_wnms_event_proto_goTypes = nil
	file_wnms_event_proto_depIdxs = nil
}
