// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: wnms_p5g.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type P5GStatsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	P5GStats      []*P5GStats            `protobuf:"bytes,1,rep,name=p5gStats,proto3" json:"p5gStats,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P5GStatsReport) Reset() {
	*x = P5GStatsReport{}
	mi := &file_wnms_p5g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P5GStatsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P5GStatsReport) ProtoMessage() {}

func (x *P5GStatsReport) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_p5g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P5GStatsReport.ProtoReflect.Descriptor instead.
func (*P5GStatsReport) Descriptor() ([]byte, []int) {
	return file_wnms_p5g_proto_rawDescGZIP(), []int{0}
}

func (x *P5GStatsReport) GetP5GStats() []*P5GStats {
	if x != nil {
		return x.P5GStats
	}
	return nil
}

func (x *P5GStatsReport) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type P5GStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          map[string]string      `protobuf:"bytes,10,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RegionCode    string                 `protobuf:"bytes,91,opt,name=regionCode,proto3" json:"regionCode,omitempty"`
	FactoryCode   string                 `protobuf:"bytes,92,opt,name=factoryCode,proto3" json:"factoryCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P5GStats) Reset() {
	*x = P5GStats{}
	mi := &file_wnms_p5g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P5GStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P5GStats) ProtoMessage() {}

func (x *P5GStats) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_p5g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P5GStats.ProtoReflect.Descriptor instead.
func (*P5GStats) Descriptor() ([]byte, []int) {
	return file_wnms_p5g_proto_rawDescGZIP(), []int{1}
}

func (x *P5GStats) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *P5GStats) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *P5GStats) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

func (x *P5GStats) GetFactoryCode() string {
	if x != nil {
		return x.FactoryCode
	}
	return ""
}

var File_wnms_p5g_proto protoreflect.FileDescriptor

const file_wnms_p5g_proto_rawDesc = "" +
	"\n" +
	"\x0ewnms_p5g.proto\x12\x1fkr.connectlabs.wnms.proto.model\"u\n" +
	"\x0eP5gStatsReport\x12E\n" +
	"\bp5gStats\x18\x01 \x03(\v2).kr.connectlabs.wnms.proto.model.P5gStatsR\bp5gStats\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\"\xde\x01\n" +
	"\bP5gStats\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12G\n" +
	"\x04data\x18\n" +
	" \x03(\v23.kr.connectlabs.wnms.proto.model.P5gStats.DataEntryR\x04data\x12\x1e\n" +
	"\n" +
	"regionCode\x18[ \x01(\tR\n" +
	"regionCode\x12 \n" +
	"\vfactoryCode\x18\\ \x01(\tR\vfactoryCode\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"Z\b../modelb\x06proto3"

var (
	file_wnms_p5g_proto_rawDescOnce sync.Once
	file_wnms_p5g_proto_rawDescData []byte
)

func file_wnms_p5g_proto_rawDescGZIP() []byte {
	file_wnms_p5g_proto_rawDescOnce.Do(func() {
		file_wnms_p5g_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wnms_p5g_proto_rawDesc), len(file_wnms_p5g_proto_rawDesc)))
	})
	return file_wnms_p5g_proto_rawDescData
}

var file_wnms_p5g_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wnms_p5g_proto_goTypes = []any{
	(*P5GStatsReport)(nil), // 0: kr.connectlabs.wnms.proto.model.P5gStatsReport
	(*P5GStats)(nil),       // 1: kr.connectlabs.wnms.proto.model.P5gStats
	nil,                    // 2: kr.connectlabs.wnms.proto.model.P5gStats.DataEntry
}
var file_wnms_p5g_proto_depIdxs = []int32{
	1, // 0: kr.connectlabs.wnms.proto.model.P5gStatsReport.p5gStats:type_name -> kr.connectlabs.wnms.proto.model.P5gStats
	2, // 1: kr.connectlabs.wnms.proto.model.P5gStats.data:type_name -> kr.connectlabs.wnms.proto.model.P5gStats.DataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wnms_p5g_proto_init() }
func file_wnms_p5g_proto_init() {
	if File_wnms_p5g_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wnms_p5g_proto_rawDesc), len(file_wnms_p5g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wnms_p5g_proto_goTypes,
		DependencyIndexes: file_wnms_p5g_proto_depIdxs,
		MessageInfos:      file_wnms_p5g_proto_msgTypes,
	}.Build()
	File_wnms_p5g_proto = out.File
	file_wnms_p5g_proto_goTypes = nil
	file_wnms_p5g_proto_depIdxs = nil
}
