// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: wnms_p5g_ue.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type P5GUeStatsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	P5GUeStats    []*P5GUeStats          `protobuf:"bytes,1,rep,name=p5gUeStats,proto3" json:"p5gUeStats,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P5GUeStatsReport) Reset() {
	*x = P5GUeStatsReport{}
	mi := &file_wnms_p5g_ue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P5GUeStatsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P5GUeStatsReport) ProtoMessage() {}

func (x *P5GUeStatsReport) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_p5g_ue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P5GUeStatsReport.ProtoReflect.Descriptor instead.
func (*P5GUeStatsReport) Descriptor() ([]byte, []int) {
	return file_wnms_p5g_ue_proto_rawDescGZIP(), []int{0}
}

func (x *P5GUeStatsReport) GetP5GUeStats() []*P5GUeStats {
	if x != nil {
		return x.P5GUeStats
	}
	return nil
}

func (x *P5GUeStatsReport) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type P5GUeSystem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuRate         float32                `protobuf:"fixed32,1,opt,name=cpuRate,proto3" json:"cpuRate,omitempty"`
	MemoryRate      float32                `protobuf:"fixed32,2,opt,name=memoryRate,proto3" json:"memoryRate,omitempty"`
	StorageRate     float32                `protobuf:"fixed32,3,opt,name=storageRate,proto3" json:"storageRate,omitempty"`
	Temperature     float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	FirmwareVersion string                 `protobuf:"bytes,5,opt,name=firmwareVersion,proto3" json:"firmwareVersion,omitempty"`
	Handle          string                 `protobuf:"bytes,6,opt,name=handle,proto3" json:"handle,omitempty"`
	StartEpoch      int64                  `protobuf:"varint,7,opt,name=startEpoch,proto3" json:"startEpoch,omitempty"`
	UptimeSecs      int64                  `protobuf:"varint,8,opt,name=uptimeSecs,proto3" json:"uptimeSecs,omitempty"`
	Commway         string                 `protobuf:"bytes,9,opt,name=commway,proto3" json:"commway,omitempty"`
	Lan1Act         int32                  `protobuf:"varint,10,opt,name=lan1Act,proto3" json:"lan1Act,omitempty"`
	Lan2Act         int32                  `protobuf:"varint,11,opt,name=lan2Act,proto3" json:"lan2Act,omitempty"`
	Wlan0Act        int32                  `protobuf:"varint,12,opt,name=wlan0Act,proto3" json:"wlan0Act,omitempty"`
	Qmimux0Act      int32                  `protobuf:"varint,13,opt,name=qmimux0Act,proto3" json:"qmimux0Act,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *P5GUeSystem) Reset() {
	*x = P5GUeSystem{}
	mi := &file_wnms_p5g_ue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P5GUeSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P5GUeSystem) ProtoMessage() {}

func (x *P5GUeSystem) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_p5g_ue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P5GUeSystem.ProtoReflect.Descriptor instead.
func (*P5GUeSystem) Descriptor() ([]byte, []int) {
	return file_wnms_p5g_ue_proto_rawDescGZIP(), []int{1}
}

func (x *P5GUeSystem) GetCpuRate() float32 {
	if x != nil {
		return x.CpuRate
	}
	return 0
}

func (x *P5GUeSystem) GetMemoryRate() float32 {
	if x != nil {
		return x.MemoryRate
	}
	return 0
}

func (x *P5GUeSystem) GetStorageRate() float32 {
	if x != nil {
		return x.StorageRate
	}
	return 0
}

func (x *P5GUeSystem) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *P5GUeSystem) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *P5GUeSystem) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *P5GUeSystem) GetStartEpoch() int64 {
	if x != nil {
		return x.StartEpoch
	}
	return 0
}

func (x *P5GUeSystem) GetUptimeSecs() int64 {
	if x != nil {
		return x.UptimeSecs
	}
	return 0
}

func (x *P5GUeSystem) GetCommway() string {
	if x != nil {
		return x.Commway
	}
	return ""
}

func (x *P5GUeSystem) GetLan1Act() int32 {
	if x != nil {
		return x.Lan1Act
	}
	return 0
}

func (x *P5GUeSystem) GetLan2Act() int32 {
	if x != nil {
		return x.Lan2Act
	}
	return 0
}

func (x *P5GUeSystem) GetWlan0Act() int32 {
	if x != nil {
		return x.Wlan0Act
	}
	return 0
}

func (x *P5GUeSystem) GetQmimux0Act() int32 {
	if x != nil {
		return x.Qmimux0Act
	}
	return 0
}

type P5GUeLan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BpsTxAvg      int64                  `protobuf:"varint,1,opt,name=bpsTxAvg,proto3" json:"bpsTxAvg,omitempty"`
	BpsTxSum      int64                  `protobuf:"varint,2,opt,name=bpsTxSum,proto3" json:"bpsTxSum,omitempty"`
	BpsRxAvg      int64                  `protobuf:"varint,3,opt,name=bpsRxAvg,proto3" json:"bpsRxAvg,omitempty"`
	BpsRxSum      int64                  `protobuf:"varint,4,opt,name=bpsRxSum,proto3" json:"bpsRxSum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P5GUeLan) Reset() {
	*x = P5GUeLan{}
	mi := &file_wnms_p5g_ue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P5GUeLan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P5GUeLan) ProtoMessage() {}

func (x *P5GUeLan) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_p5g_ue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P5GUeLan.ProtoReflect.Descriptor instead.
func (*P5GUeLan) Descriptor() ([]byte, []int) {
	return file_wnms_p5g_ue_proto_rawDescGZIP(), []int{2}
}

func (x *P5GUeLan) GetBpsTxAvg() int64 {
	if x != nil {
		return x.BpsTxAvg
	}
	return 0
}

func (x *P5GUeLan) GetBpsTxSum() int64 {
	if x != nil {
		return x.BpsTxSum
	}
	return 0
}

func (x *P5GUeLan) GetBpsRxAvg() int64 {
	if x != nil {
		return x.BpsRxAvg
	}
	return 0
}

func (x *P5GUeLan) GetBpsRxSum() int64 {
	if x != nil {
		return x.BpsRxSum
	}
	return 0
}

type P5GUeWlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     string                 `protobuf:"bytes,1,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	MacAddress    string                 `protobuf:"bytes,2,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	BpsTxAvg      int64                  `protobuf:"varint,3,opt,name=bpsTxAvg,proto3" json:"bpsTxAvg,omitempty"`
	BpsTxSum      int64                  `protobuf:"varint,4,opt,name=bpsTxSum,proto3" json:"bpsTxSum,omitempty"`
	BpsRxAvg      int64                  `protobuf:"varint,5,opt,name=bpsRxAvg,proto3" json:"bpsRxAvg,omitempty"`
	BpsRxSum      int64                  `protobuf:"varint,6,opt,name=bpsRxSum,proto3" json:"bpsRxSum,omitempty"`
	Rssi          int32                  `protobuf:"varint,7,opt,name=rssi,proto3" json:"rssi,omitempty"`
	NoiseLevel    int32                  `protobuf:"varint,8,opt,name=noiseLevel,proto3" json:"noiseLevel,omitempty"`
	AntA          int32                  `protobuf:"varint,9,opt,name=antA,proto3" json:"antA,omitempty"`
	AntB          int32                  `protobuf:"varint,10,opt,name=antB,proto3" json:"antB,omitempty"`
	McsTx         int64                  `protobuf:"varint,11,opt,name=mcsTx,proto3" json:"mcsTx,omitempty"`
	McsRx         int64                  `protobuf:"varint,12,opt,name=mcsRx,proto3" json:"mcsRx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P5GUeWlan) Reset() {
	*x = P5GUeWlan{}
	mi := &file_wnms_p5g_ue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P5GUeWlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P5GUeWlan) ProtoMessage() {}

func (x *P5GUeWlan) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_p5g_ue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P5GUeWlan.ProtoReflect.Descriptor instead.
func (*P5GUeWlan) Descriptor() ([]byte, []int) {
	return file_wnms_p5g_ue_proto_rawDescGZIP(), []int{3}
}

func (x *P5GUeWlan) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *P5GUeWlan) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *P5GUeWlan) GetBpsTxAvg() int64 {
	if x != nil {
		return x.BpsTxAvg
	}
	return 0
}

func (x *P5GUeWlan) GetBpsTxSum() int64 {
	if x != nil {
		return x.BpsTxSum
	}
	return 0
}

func (x *P5GUeWlan) GetBpsRxAvg() int64 {
	if x != nil {
		return x.BpsRxAvg
	}
	return 0
}

func (x *P5GUeWlan) GetBpsRxSum() int64 {
	if x != nil {
		return x.BpsRxSum
	}
	return 0
}

func (x *P5GUeWlan) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *P5GUeWlan) GetNoiseLevel() int32 {
	if x != nil {
		return x.NoiseLevel
	}
	return 0
}

func (x *P5GUeWlan) GetAntA() int32 {
	if x != nil {
		return x.AntA
	}
	return 0
}

func (x *P5GUeWlan) GetAntB() int32 {
	if x != nil {
		return x.AntB
	}
	return 0
}

func (x *P5GUeWlan) GetMcsTx() int64 {
	if x != nil {
		return x.McsTx
	}
	return 0
}

func (x *P5GUeWlan) GetMcsRx() int64 {
	if x != nil {
		return x.McsRx
	}
	return 0
}

type P5GUeQmimux struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     string                 `protobuf:"bytes,1,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	Imei          string                 `protobuf:"bytes,2,opt,name=imei,proto3" json:"imei,omitempty"`
	Imsi          string                 `protobuf:"bytes,3,opt,name=imsi,proto3" json:"imsi,omitempty"`
	Pcid          string                 `protobuf:"bytes,11,opt,name=pcid,proto3" json:"pcid,omitempty"`
	Tac           int32                  `protobuf:"varint,12,opt,name=tac,proto3" json:"tac,omitempty"`
	Rsrp          int32                  `protobuf:"varint,13,opt,name=rsrp,proto3" json:"rsrp,omitempty"`
	Rsrq          int32                  `protobuf:"varint,14,opt,name=rsrq,proto3" json:"rsrq,omitempty"`
	Rssi          int32                  `protobuf:"varint,15,opt,name=rssi,proto3" json:"rssi,omitempty"`
	Cqi           int32                  `protobuf:"varint,16,opt,name=cqi,proto3" json:"cqi,omitempty"`
	Ri            int32                  `protobuf:"varint,17,opt,name=ri,proto3" json:"ri,omitempty"`
	Rb            int32                  `protobuf:"varint,18,opt,name=rb,proto3" json:"rb,omitempty"`
	McsTx         int64                  `protobuf:"varint,21,opt,name=mcsTx,proto3" json:"mcsTx,omitempty"`
	McsRx         int64                  `protobuf:"varint,22,opt,name=mcsRx,proto3" json:"mcsRx,omitempty"`
	BpsTxAvg      int64                  `protobuf:"varint,23,opt,name=bpsTxAvg,proto3" json:"bpsTxAvg,omitempty"`
	BpsTxSum      int64                  `protobuf:"varint,24,opt,name=bpsTxSum,proto3" json:"bpsTxSum,omitempty"`
	BpsRxAvg      int64                  `protobuf:"varint,25,opt,name=bpsRxAvg,proto3" json:"bpsRxAvg,omitempty"`
	BpsRxSum      int64                  `protobuf:"varint,26,opt,name=bpsRxSum,proto3" json:"bpsRxSum,omitempty"`
	Ant0Power     float32                `protobuf:"fixed32,31,opt,name=ant0Power,proto3" json:"ant0Power,omitempty"`
	Ant0Ecio      float32                `protobuf:"fixed32,32,opt,name=ant0Ecio,proto3" json:"ant0Ecio,omitempty"`
	Ant0Rsrp      float32                `protobuf:"fixed32,33,opt,name=ant0Rsrp,proto3" json:"ant0Rsrp,omitempty"`
	Ant1Power     float32                `protobuf:"fixed32,34,opt,name=ant1Power,proto3" json:"ant1Power,omitempty"`
	Ant1Ecio      float32                `protobuf:"fixed32,35,opt,name=ant1Ecio,proto3" json:"ant1Ecio,omitempty"`
	Ant1Rsrp      float32                `protobuf:"fixed32,36,opt,name=ant1Rsrp,proto3" json:"ant1Rsrp,omitempty"`
	Ant2Power     float32                `protobuf:"fixed32,37,opt,name=ant2Power,proto3" json:"ant2Power,omitempty"`
	Ant2Ecio      float32                `protobuf:"fixed32,38,opt,name=ant2Ecio,proto3" json:"ant2Ecio,omitempty"`
	Ant2Rsrp      float32                `protobuf:"fixed32,39,opt,name=ant2Rsrp,proto3" json:"ant2Rsrp,omitempty"`
	Ant3Power     float32                `protobuf:"fixed32,40,opt,name=ant3Power,proto3" json:"ant3Power,omitempty"`
	Ant3Ecio      float32                `protobuf:"fixed32,41,opt,name=ant3Ecio,proto3" json:"ant3Ecio,omitempty"`
	Ant3Rsrp      float32                `protobuf:"fixed32,42,opt,name=ant3Rsrp,proto3" json:"ant3Rsrp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P5GUeQmimux) Reset() {
	*x = P5GUeQmimux{}
	mi := &file_wnms_p5g_ue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P5GUeQmimux) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P5GUeQmimux) ProtoMessage() {}

func (x *P5GUeQmimux) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_p5g_ue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P5GUeQmimux.ProtoReflect.Descriptor instead.
func (*P5GUeQmimux) Descriptor() ([]byte, []int) {
	return file_wnms_p5g_ue_proto_rawDescGZIP(), []int{4}
}

func (x *P5GUeQmimux) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *P5GUeQmimux) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *P5GUeQmimux) GetImsi() string {
	if x != nil {
		return x.Imsi
	}
	return ""
}

func (x *P5GUeQmimux) GetPcid() string {
	if x != nil {
		return x.Pcid
	}
	return ""
}

func (x *P5GUeQmimux) GetTac() int32 {
	if x != nil {
		return x.Tac
	}
	return 0
}

func (x *P5GUeQmimux) GetRsrp() int32 {
	if x != nil {
		return x.Rsrp
	}
	return 0
}

func (x *P5GUeQmimux) GetRsrq() int32 {
	if x != nil {
		return x.Rsrq
	}
	return 0
}

func (x *P5GUeQmimux) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *P5GUeQmimux) GetCqi() int32 {
	if x != nil {
		return x.Cqi
	}
	return 0
}

func (x *P5GUeQmimux) GetRi() int32 {
	if x != nil {
		return x.Ri
	}
	return 0
}

func (x *P5GUeQmimux) GetRb() int32 {
	if x != nil {
		return x.Rb
	}
	return 0
}

func (x *P5GUeQmimux) GetMcsTx() int64 {
	if x != nil {
		return x.McsTx
	}
	return 0
}

func (x *P5GUeQmimux) GetMcsRx() int64 {
	if x != nil {
		return x.McsRx
	}
	return 0
}

func (x *P5GUeQmimux) GetBpsTxAvg() int64 {
	if x != nil {
		return x.BpsTxAvg
	}
	return 0
}

func (x *P5GUeQmimux) GetBpsTxSum() int64 {
	if x != nil {
		return x.BpsTxSum
	}
	return 0
}

func (x *P5GUeQmimux) GetBpsRxAvg() int64 {
	if x != nil {
		return x.BpsRxAvg
	}
	return 0
}

func (x *P5GUeQmimux) GetBpsRxSum() int64 {
	if x != nil {
		return x.BpsRxSum
	}
	return 0
}

func (x *P5GUeQmimux) GetAnt0Power() float32 {
	if x != nil {
		return x.Ant0Power
	}
	return 0
}

func (x *P5GUeQmimux) GetAnt0Ecio() float32 {
	if x != nil {
		return x.Ant0Ecio
	}
	return 0
}

func (x *P5GUeQmimux) GetAnt0Rsrp() float32 {
	if x != nil {
		return x.Ant0Rsrp
	}
	return 0
}

func (x *P5GUeQmimux) GetAnt1Power() float32 {
	if x != nil {
		return x.Ant1Power
	}
	return 0
}

func (x *P5GUeQmimux) GetAnt1Ecio() float32 {
	if x != nil {
		return x.Ant1Ecio
	}
	return 0
}

func (x *P5GUeQmimux) GetAnt1Rsrp() float32 {
	if x != nil {
		return x.Ant1Rsrp
	}
	return 0
}

func (x *P5GUeQmimux) GetAnt2Power() float32 {
	if x != nil {
		return x.Ant2Power
	}
	return 0
}

func (x *P5GUeQmimux) GetAnt2Ecio() float32 {
	if x != nil {
		return x.Ant2Ecio
	}
	return 0
}

func (x *P5GUeQmimux) GetAnt2Rsrp() float32 {
	if x != nil {
		return x.Ant2Rsrp
	}
	return 0
}

func (x *P5GUeQmimux) GetAnt3Power() float32 {
	if x != nil {
		return x.Ant3Power
	}
	return 0
}

func (x *P5GUeQmimux) GetAnt3Ecio() float32 {
	if x != nil {
		return x.Ant3Ecio
	}
	return 0
}

func (x *P5GUeQmimux) GetAnt3Rsrp() float32 {
	if x != nil {
		return x.Ant3Rsrp
	}
	return 0
}

type P5GUeLoc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PosX          float32                `protobuf:"fixed32,1,opt,name=PosX,proto3" json:"PosX,omitempty"`
	PosY          float32                `protobuf:"fixed32,2,opt,name=PosY,proto3" json:"PosY,omitempty"`
	Angle         float32                `protobuf:"fixed32,3,opt,name=Angle,proto3" json:"Angle,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P5GUeLoc) Reset() {
	*x = P5GUeLoc{}
	mi := &file_wnms_p5g_ue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P5GUeLoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P5GUeLoc) ProtoMessage() {}

func (x *P5GUeLoc) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_p5g_ue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P5GUeLoc.ProtoReflect.Descriptor instead.
func (*P5GUeLoc) Descriptor() ([]byte, []int) {
	return file_wnms_p5g_ue_proto_rawDescGZIP(), []int{5}
}

func (x *P5GUeLoc) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *P5GUeLoc) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *P5GUeLoc) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *P5GUeLoc) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type P5GUeStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DeviceName    string                 `protobuf:"bytes,2,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	ModelName     string                 `protobuf:"bytes,3,opt,name=modelName,proto3" json:"modelName,omitempty"`
	GroupName     string                 `protobuf:"bytes,4,opt,name=groupName,proto3" json:"groupName,omitempty"`
	System        *P5GUeSystem           `protobuf:"bytes,11,opt,name=system,proto3" json:"system,omitempty"`
	Lan1          *P5GUeLan              `protobuf:"bytes,21,opt,name=lan1,proto3" json:"lan1,omitempty"`
	Lan2          *P5GUeLan              `protobuf:"bytes,22,opt,name=lan2,proto3" json:"lan2,omitempty"`
	Wlan0         *P5GUeWlan             `protobuf:"bytes,31,opt,name=wlan0,proto3" json:"wlan0,omitempty"`
	Qmimux0       *P5GUeQmimux           `protobuf:"bytes,41,opt,name=qmimux0,proto3" json:"qmimux0,omitempty"`
	Location      *P5GUeLoc              `protobuf:"bytes,51,opt,name=location,proto3" json:"location,omitempty"`
	Dtc           []string               `protobuf:"bytes,61,rep,name=dtc,proto3" json:"dtc,omitempty"`
	RegionCode    string                 `protobuf:"bytes,91,opt,name=regionCode,proto3" json:"regionCode,omitempty"`
	FactoryCode   string                 `protobuf:"bytes,92,opt,name=factoryCode,proto3" json:"factoryCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P5GUeStats) Reset() {
	*x = P5GUeStats{}
	mi := &file_wnms_p5g_ue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P5GUeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P5GUeStats) ProtoMessage() {}

func (x *P5GUeStats) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_p5g_ue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P5GUeStats.ProtoReflect.Descriptor instead.
func (*P5GUeStats) Descriptor() ([]byte, []int) {
	return file_wnms_p5g_ue_proto_rawDescGZIP(), []int{6}
}

func (x *P5GUeStats) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *P5GUeStats) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *P5GUeStats) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *P5GUeStats) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *P5GUeStats) GetSystem() *P5GUeSystem {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *P5GUeStats) GetLan1() *P5GUeLan {
	if x != nil {
		return x.Lan1
	}
	return nil
}

func (x *P5GUeStats) GetLan2() *P5GUeLan {
	if x != nil {
		return x.Lan2
	}
	return nil
}

func (x *P5GUeStats) GetWlan0() *P5GUeWlan {
	if x != nil {
		return x.Wlan0
	}
	return nil
}

func (x *P5GUeStats) GetQmimux0() *P5GUeQmimux {
	if x != nil {
		return x.Qmimux0
	}
	return nil
}

func (x *P5GUeStats) GetLocation() *P5GUeLoc {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *P5GUeStats) GetDtc() []string {
	if x != nil {
		return x.Dtc
	}
	return nil
}

func (x *P5GUeStats) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

func (x *P5GUeStats) GetFactoryCode() string {
	if x != nil {
		return x.FactoryCode
	}
	return ""
}

var File_wnms_p5g_ue_proto protoreflect.FileDescriptor

const file_wnms_p5g_ue_proto_rawDesc = "" +
	"\n" +
	"\x11wnms_p5g_ue.proto\x12\x1fkr.connectlabs.wnms.proto.model\"}\n" +
	"\x10P5gUeStatsReport\x12K\n" +
	"\n" +
	"p5gUeStats\x18\x01 \x03(\v2+.kr.connectlabs.wnms.proto.model.P5gUeStatsR\n" +
	"p5gUeStats\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\"\x97\x03\n" +
	"\vP5gUeSystem\x12\x18\n" +
	"\acpuRate\x18\x01 \x01(\x02R\acpuRate\x12\x1e\n" +
	"\n" +
	"memoryRate\x18\x02 \x01(\x02R\n" +
	"memoryRate\x12 \n" +
	"\vstorageRate\x18\x03 \x01(\x02R\vstorageRate\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12(\n" +
	"\x0ffirmwareVersion\x18\x05 \x01(\tR\x0ffirmwareVersion\x12\x16\n" +
	"\x06handle\x18\x06 \x01(\tR\x06handle\x12\x1e\n" +
	"\n" +
	"startEpoch\x18\a \x01(\x03R\n" +
	"startEpoch\x12\x1e\n" +
	"\n" +
	"uptimeSecs\x18\b \x01(\x03R\n" +
	"uptimeSecs\x12\x18\n" +
	"\acommway\x18\t \x01(\tR\acommway\x12\x18\n" +
	"\alan1Act\x18\n" +
	" \x01(\x05R\alan1Act\x12\x18\n" +
	"\alan2Act\x18\v \x01(\x05R\alan2Act\x12\x1a\n" +
	"\bwlan0Act\x18\f \x01(\x05R\bwlan0Act\x12\x1e\n" +
	"\n" +
	"qmimux0Act\x18\r \x01(\x05R\n" +
	"qmimux0Act\"z\n" +
	"\bP5gUeLan\x12\x1a\n" +
	"\bbpsTxAvg\x18\x01 \x01(\x03R\bbpsTxAvg\x12\x1a\n" +
	"\bbpsTxSum\x18\x02 \x01(\x03R\bbpsTxSum\x12\x1a\n" +
	"\bbpsRxAvg\x18\x03 \x01(\x03R\bbpsRxAvg\x12\x1a\n" +
	"\bbpsRxSum\x18\x04 \x01(\x03R\bbpsRxSum\"\xc1\x02\n" +
	"\tP5gUeWlan\x12\x1c\n" +
	"\tipAddress\x18\x01 \x01(\tR\tipAddress\x12\x1e\n" +
	"\n" +
	"macAddress\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x1a\n" +
	"\bbpsTxAvg\x18\x03 \x01(\x03R\bbpsTxAvg\x12\x1a\n" +
	"\bbpsTxSum\x18\x04 \x01(\x03R\bbpsTxSum\x12\x1a\n" +
	"\bbpsRxAvg\x18\x05 \x01(\x03R\bbpsRxAvg\x12\x1a\n" +
	"\bbpsRxSum\x18\x06 \x01(\x03R\bbpsRxSum\x12\x12\n" +
	"\x04rssi\x18\a \x01(\x05R\x04rssi\x12\x1e\n" +
	"\n" +
	"noiseLevel\x18\b \x01(\x05R\n" +
	"noiseLevel\x12\x12\n" +
	"\x04antA\x18\t \x01(\x05R\x04antA\x12\x12\n" +
	"\x04antB\x18\n" +
	" \x01(\x05R\x04antB\x12\x14\n" +
	"\x05mcsTx\x18\v \x01(\x03R\x05mcsTx\x12\x14\n" +
	"\x05mcsRx\x18\f \x01(\x03R\x05mcsRx\"\xdb\x05\n" +
	"\vP5gUeQmimux\x12\x1c\n" +
	"\tipAddress\x18\x01 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04imei\x18\x02 \x01(\tR\x04imei\x12\x12\n" +
	"\x04imsi\x18\x03 \x01(\tR\x04imsi\x12\x12\n" +
	"\x04pcid\x18\v \x01(\tR\x04pcid\x12\x10\n" +
	"\x03tac\x18\f \x01(\x05R\x03tac\x12\x12\n" +
	"\x04rsrp\x18\r \x01(\x05R\x04rsrp\x12\x12\n" +
	"\x04rsrq\x18\x0e \x01(\x05R\x04rsrq\x12\x12\n" +
	"\x04rssi\x18\x0f \x01(\x05R\x04rssi\x12\x10\n" +
	"\x03cqi\x18\x10 \x01(\x05R\x03cqi\x12\x0e\n" +
	"\x02ri\x18\x11 \x01(\x05R\x02ri\x12\x0e\n" +
	"\x02rb\x18\x12 \x01(\x05R\x02rb\x12\x14\n" +
	"\x05mcsTx\x18\x15 \x01(\x03R\x05mcsTx\x12\x14\n" +
	"\x05mcsRx\x18\x16 \x01(\x03R\x05mcsRx\x12\x1a\n" +
	"\bbpsTxAvg\x18\x17 \x01(\x03R\bbpsTxAvg\x12\x1a\n" +
	"\bbpsTxSum\x18\x18 \x01(\x03R\bbpsTxSum\x12\x1a\n" +
	"\bbpsRxAvg\x18\x19 \x01(\x03R\bbpsRxAvg\x12\x1a\n" +
	"\bbpsRxSum\x18\x1a \x01(\x03R\bbpsRxSum\x12\x1c\n" +
	"\tant0Power\x18\x1f \x01(\x02R\tant0Power\x12\x1a\n" +
	"\bant0Ecio\x18  \x01(\x02R\bant0Ecio\x12\x1a\n" +
	"\bant0Rsrp\x18! \x01(\x02R\bant0Rsrp\x12\x1c\n" +
	"\tant1Power\x18\" \x01(\x02R\tant1Power\x12\x1a\n" +
	"\bant1Ecio\x18# \x01(\x02R\bant1Ecio\x12\x1a\n" +
	"\bant1Rsrp\x18$ \x01(\x02R\bant1Rsrp\x12\x1c\n" +
	"\tant2Power\x18% \x01(\x02R\tant2Power\x12\x1a\n" +
	"\bant2Ecio\x18& \x01(\x02R\bant2Ecio\x12\x1a\n" +
	"\bant2Rsrp\x18' \x01(\x02R\bant2Rsrp\x12\x1c\n" +
	"\tant3Power\x18( \x01(\x02R\tant3Power\x12\x1a\n" +
	"\bant3Ecio\x18) \x01(\x02R\bant3Ecio\x12\x1a\n" +
	"\bant3Rsrp\x18* \x01(\x02R\bant3Rsrp\"`\n" +
	"\bP5gUeLoc\x12\x12\n" +
	"\x04PosX\x18\x01 \x01(\x02R\x04PosX\x12\x12\n" +
	"\x04PosY\x18\x02 \x01(\x02R\x04PosY\x12\x14\n" +
	"\x05Angle\x18\x03 \x01(\x02R\x05Angle\x12\x16\n" +
	"\x06Status\x18\x04 \x01(\x05R\x06Status\"\xef\x04\n" +
	"\n" +
	"P5gUeStats\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1e\n" +
	"\n" +
	"deviceName\x18\x02 \x01(\tR\n" +
	"deviceName\x12\x1c\n" +
	"\tmodelName\x18\x03 \x01(\tR\tmodelName\x12\x1c\n" +
	"\tgroupName\x18\x04 \x01(\tR\tgroupName\x12D\n" +
	"\x06system\x18\v \x01(\v2,.kr.connectlabs.wnms.proto.model.P5gUeSystemR\x06system\x12=\n" +
	"\x04lan1\x18\x15 \x01(\v2).kr.connectlabs.wnms.proto.model.P5gUeLanR\x04lan1\x12=\n" +
	"\x04lan2\x18\x16 \x01(\v2).kr.connectlabs.wnms.proto.model.P5gUeLanR\x04lan2\x12@\n" +
	"\x05wlan0\x18\x1f \x01(\v2*.kr.connectlabs.wnms.proto.model.P5gUeWlanR\x05wlan0\x12F\n" +
	"\aqmimux0\x18) \x01(\v2,.kr.connectlabs.wnms.proto.model.P5gUeQmimuxR\aqmimux0\x12E\n" +
	"\blocation\x183 \x01(\v2).kr.connectlabs.wnms.proto.model.P5gUeLocR\blocation\x12\x10\n" +
	"\x03dtc\x18= \x03(\tR\x03dtc\x12\x1e\n" +
	"\n" +
	"regionCode\x18[ \x01(\tR\n" +
	"regionCode\x12 \n" +
	"\vfactoryCode\x18\\ \x01(\tR\vfactoryCodeB\n" +
	"Z\b../modelb\x06proto3"

var (
	file_wnms_p5g_ue_proto_rawDescOnce sync.Once
	file_wnms_p5g_ue_proto_rawDescData []byte
)

func file_wnms_p5g_ue_proto_rawDescGZIP() []byte {
	file_wnms_p5g_ue_proto_rawDescOnce.Do(func() {
		file_wnms_p5g_ue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wnms_p5g_ue_proto_rawDesc), len(file_wnms_p5g_ue_proto_rawDesc)))
	})
	return file_wnms_p5g_ue_proto_rawDescData
}

var file_wnms_p5g_ue_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_wnms_p5g_ue_proto_goTypes = []any{
	(*P5GUeStatsReport)(nil), // 0: kr.connectlabs.wnms.proto.model.P5gUeStatsReport
	(*P5GUeSystem)(nil),      // 1: kr.connectlabs.wnms.proto.model.P5gUeSystem
	(*P5GUeLan)(nil),         // 2: kr.connectlabs.wnms.proto.model.P5gUeLan
	(*P5GUeWlan)(nil),        // 3: kr.connectlabs.wnms.proto.model.P5gUeWlan
	(*P5GUeQmimux)(nil),      // 4: kr.connectlabs.wnms.proto.model.P5gUeQmimux
	(*P5GUeLoc)(nil),         // 5: kr.connectlabs.wnms.proto.model.P5gUeLoc
	(*P5GUeStats)(nil),       // 6: kr.connectlabs.wnms.proto.model.P5gUeStats
}
var file_wnms_p5g_ue_proto_depIdxs = []int32{
	6, // 0: kr.connectlabs.wnms.proto.model.P5gUeStatsReport.p5gUeStats:type_name -> kr.connectlabs.wnms.proto.model.P5gUeStats
	1, // 1: kr.connectlabs.wnms.proto.model.P5gUeStats.system:type_name -> kr.connectlabs.wnms.proto.model.P5gUeSystem
	2, // 2: kr.connectlabs.wnms.proto.model.P5gUeStats.lan1:type_name -> kr.connectlabs.wnms.proto.model.P5gUeLan
	2, // 3: kr.connectlabs.wnms.proto.model.P5gUeStats.lan2:type_name -> kr.connectlabs.wnms.proto.model.P5gUeLan
	3, // 4: kr.connectlabs.wnms.proto.model.P5gUeStats.wlan0:type_name -> kr.connectlabs.wnms.proto.model.P5gUeWlan
	4, // 5: kr.connectlabs.wnms.proto.model.P5gUeStats.qmimux0:type_name -> kr.connectlabs.wnms.proto.model.P5gUeQmimux
	5, // 6: kr.connectlabs.wnms.proto.model.P5gUeStats.location:type_name -> kr.connectlabs.wnms.proto.model.P5gUeLoc
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_wnms_p5g_ue_proto_init() }
func file_wnms_p5g_ue_proto_init() {
	if File_wnms_p5g_ue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wnms_p5g_ue_proto_rawDesc), len(file_wnms_p5g_ue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wnms_p5g_ue_proto_goTypes,
		DependencyIndexes: file_wnms_p5g_ue_proto_depIdxs,
		MessageInfos:      file_wnms_p5g_ue_proto_msgTypes,
	}.Build()
	File_wnms_p5g_ue_proto = out.File
	file_wnms_p5g_ue_proto_goTypes = nil
	file_wnms_p5g_ue_proto_depIdxs = nil
}
