// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: wnms_client.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApMac         string                 `protobuf:"bytes,1,opt,name=apMac,proto3" json:"apMac,omitempty"`
	ApIp          string                 `protobuf:"bytes,2,opt,name=apIp,proto3" json:"apIp,omitempty"`
	ClientList    []*ClientInfo          `protobuf:"bytes,3,rep,name=clientList,proto3" json:"clientList,omitempty"`
	ClientNum     int32                  `protobuf:"varint,4,opt,name=clientNum,proto3" json:"clientNum,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientReport) Reset() {
	*x = ClientReport{}
	mi := &file_wnms_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReport) ProtoMessage() {}

func (x *ClientReport) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReport.ProtoReflect.Descriptor instead.
func (*ClientReport) Descriptor() ([]byte, []int) {
	return file_wnms_client_proto_rawDescGZIP(), []int{0}
}

func (x *ClientReport) GetApMac() string {
	if x != nil {
		return x.ApMac
	}
	return ""
}

func (x *ClientReport) GetApIp() string {
	if x != nil {
		return x.ApIp
	}
	return ""
}

func (x *ClientReport) GetClientList() []*ClientInfo {
	if x != nil {
		return x.ClientList
	}
	return nil
}

func (x *ClientReport) GetClientNum() int32 {
	if x != nil {
		return x.ClientNum
	}
	return 0
}

func (x *ClientReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ClientInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description MAC address of the client
	// @since 3.5
	Mac string `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description IP address of the client
	// @since 3.5
	IpAddress        string             `protobuf:"bytes,2,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	RadioMode        string             `protobuf:"bytes,3,opt,name=radioMode,proto3" json:"radioMode,omitempty"`
	Ap80211RadioMode *string            `protobuf:"bytes,4,opt,name=ap80211RadioMode,proto3,oneof" json:"ap80211RadioMode,omitempty"`
	AuthMethod       string             `protobuf:"bytes,5,opt,name=authMethod,proto3" json:"authMethod,omitempty"`
	EncryptMethod    *string            `protobuf:"bytes,6,opt,name=encryptMethod,proto3,oneof" json:"encryptMethod,omitempty"`
	Bssid            string             `protobuf:"bytes,7,opt,name=bssid,proto3" json:"bssid,omitempty"`
	Ssid             string             `protobuf:"bytes,8,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Username         *string            `protobuf:"bytes,9,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Vlan             int32              `protobuf:"varint,10,opt,name=vlan,proto3" json:"vlan,omitempty"`
	OsType           *string            `protobuf:"bytes,11,opt,name=osType,proto3,oneof" json:"osType,omitempty"`
	Hostname         string             `protobuf:"bytes,12,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Channel          int32              `protobuf:"varint,13,opt,name=channel,proto3" json:"channel,omitempty"`
	ChannelWidth     int32              `protobuf:"varint,14,opt,name=channelWidth,proto3" json:"channelWidth,omitempty"`
	Rssi             int32              `protobuf:"varint,15,opt,name=rssi,proto3" json:"rssi,omitempty"`
	MaxRssi          *int32             `protobuf:"varint,16,opt,name=maxRssi,proto3,oneof" json:"maxRssi,omitempty"`
	MinRssi          *int32             `protobuf:"varint,17,opt,name=minRssi,proto3,oneof" json:"minRssi,omitempty"`
	FirstRssi        *int32             `protobuf:"varint,18,opt,name=firstRssi,proto3,oneof" json:"firstRssi,omitempty"`
	NoiseFloor       int32              `protobuf:"varint,19,opt,name=noiseFloor,proto3" json:"noiseFloor,omitempty"`
	Snr              int32              `protobuf:"varint,20,opt,name=snr,proto3" json:"snr,omitempty"`
	Location         string             `protobuf:"bytes,21,opt,name=location,proto3" json:"location,omitempty"`
	SessionId        string             `protobuf:"bytes,22,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	IpAssignTime     *uint64            `protobuf:"varint,23,opt,name=ipAssignTime,proto3,oneof" json:"ipAssignTime,omitempty"`
	SessionTime      uint64             `protobuf:"varint,24,opt,name=sessionTime,proto3" json:"sessionTime,omitempty"`
	RadioId          uint64             `protobuf:"varint,25,opt,name=radioId,proto3" json:"radioId,omitempty"`
	WsgWlanId        *uint64            `protobuf:"varint,26,opt,name=wsgWlanId,proto3,oneof" json:"wsgWlanId,omitempty"`
	WlanGroupId      *string            `protobuf:"bytes,27,opt,name=wlanGroupId,proto3,oneof" json:"wlanGroupId,omitempty"`
	MedianTxMCSRate  uint64             `protobuf:"varint,28,opt,name=medianTxMCSRate,proto3" json:"medianTxMCSRate,omitempty"`
	MedianRxMCSRate  uint64             `protobuf:"varint,29,opt,name=medianRxMCSRate,proto3" json:"medianRxMCSRate,omitempty"`
	DeviceType       *int32             `protobuf:"varint,30,opt,name=deviceType,proto3,oneof" json:"deviceType,omitempty"`
	OsVendorType     *uint64            `protobuf:"varint,31,opt,name=osVendorType,proto3,oneof" json:"osVendorType,omitempty"`
	TxPer            uint64             `protobuf:"varint,32,opt,name=txPer,proto3" json:"txPer,omitempty"`
	Traffic          *ClientTrafficInfo `protobuf:"bytes,33,opt,name=traffic,proto3" json:"traffic,omitempty"`
	CpIp             *string            `protobuf:"bytes,51,opt,name=cpIp,proto3,oneof" json:"cpIp,omitempty"`
	DpIp             *string            `protobuf:"bytes,52,opt,name=dpIp,proto3,oneof" json:"dpIp,omitempty"`
	MldAddress       *string            `protobuf:"bytes,71,opt,name=mldAddress,proto3,oneof" json:"mldAddress,omitempty"`
	RegionCode       string             `protobuf:"bytes,91,opt,name=regionCode,proto3" json:"regionCode,omitempty"`
	FactoryCode      string             `protobuf:"bytes,92,opt,name=factoryCode,proto3" json:"factoryCode,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_wnms_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_wnms_client_proto_rawDescGZIP(), []int{1}
}

func (x *ClientInfo) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *ClientInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ClientInfo) GetRadioMode() string {
	if x != nil {
		return x.RadioMode
	}
	return ""
}

func (x *ClientInfo) GetAp80211RadioMode() string {
	if x != nil && x.Ap80211RadioMode != nil {
		return *x.Ap80211RadioMode
	}
	return ""
}

func (x *ClientInfo) GetAuthMethod() string {
	if x != nil {
		return x.AuthMethod
	}
	return ""
}

func (x *ClientInfo) GetEncryptMethod() string {
	if x != nil && x.EncryptMethod != nil {
		return *x.EncryptMethod
	}
	return ""
}

func (x *ClientInfo) GetBssid() string {
	if x != nil {
		return x.Bssid
	}
	return ""
}

func (x *ClientInfo) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *ClientInfo) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *ClientInfo) GetVlan() int32 {
	if x != nil {
		return x.Vlan
	}
	return 0
}

func (x *ClientInfo) GetOsType() string {
	if x != nil && x.OsType != nil {
		return *x.OsType
	}
	return ""
}

func (x *ClientInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ClientInfo) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ClientInfo) GetChannelWidth() int32 {
	if x != nil {
		return x.ChannelWidth
	}
	return 0
}

func (x *ClientInfo) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *ClientInfo) GetMaxRssi() int32 {
	if x != nil && x.MaxRssi != nil {
		return *x.MaxRssi
	}
	return 0
}

func (x *ClientInfo) GetMinRssi() int32 {
	if x != nil && x.MinRssi != nil {
		return *x.MinRssi
	}
	return 0
}

func (x *ClientInfo) GetFirstRssi() int32 {
	if x != nil && x.FirstRssi != nil {
		return *x.FirstRssi
	}
	return 0
}

func (x *ClientInfo) GetNoiseFloor() int32 {
	if x != nil {
		return x.NoiseFloor
	}
	return 0
}

func (x *ClientInfo) GetSnr() int32 {
	if x != nil {
		return x.Snr
	}
	return 0
}

func (x *ClientInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ClientInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientInfo) GetIpAssignTime() uint64 {
	if x != nil && x.IpAssignTime != nil {
		return *x.IpAssignTime
	}
	return 0
}

func (x *ClientInfo) GetSessionTime() uint64 {
	if x != nil {
		return x.SessionTime
	}
	return 0
}

func (x *ClientInfo) GetRadioId() uint64 {
	if x != nil {
		return x.RadioId
	}
	return 0
}

func (x *ClientInfo) GetWsgWlanId() uint64 {
	if x != nil && x.WsgWlanId != nil {
		return *x.WsgWlanId
	}
	return 0
}

func (x *ClientInfo) GetWlanGroupId() string {
	if x != nil && x.WlanGroupId != nil {
		return *x.WlanGroupId
	}
	return ""
}

func (x *ClientInfo) GetMedianTxMCSRate() uint64 {
	if x != nil {
		return x.MedianTxMCSRate
	}
	return 0
}

func (x *ClientInfo) GetMedianRxMCSRate() uint64 {
	if x != nil {
		return x.MedianRxMCSRate
	}
	return 0
}

func (x *ClientInfo) GetDeviceType() int32 {
	if x != nil && x.DeviceType != nil {
		return *x.DeviceType
	}
	return 0
}

func (x *ClientInfo) GetOsVendorType() uint64 {
	if x != nil && x.OsVendorType != nil {
		return *x.OsVendorType
	}
	return 0
}

func (x *ClientInfo) GetTxPer() uint64 {
	if x != nil {
		return x.TxPer
	}
	return 0
}

func (x *ClientInfo) GetTraffic() *ClientTrafficInfo {
	if x != nil {
		return x.Traffic
	}
	return nil
}

func (x *ClientInfo) GetCpIp() string {
	if x != nil && x.CpIp != nil {
		return *x.CpIp
	}
	return ""
}

func (x *ClientInfo) GetDpIp() string {
	if x != nil && x.DpIp != nil {
		return *x.DpIp
	}
	return ""
}

func (x *ClientInfo) GetMldAddress() string {
	if x != nil && x.MldAddress != nil {
		return *x.MldAddress
	}
	return ""
}

func (x *ClientInfo) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

func (x *ClientInfo) GetFactoryCode() string {
	if x != nil {
		return x.FactoryCode
	}
	return ""
}

type ClientTrafficInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RxBytes              int64                  `protobuf:"varint,1,opt,name=rxBytes,proto3" json:"rxBytes,omitempty"`
	TxBytes              int64                  `protobuf:"varint,2,opt,name=txBytes,proto3" json:"txBytes,omitempty"`
	RxPackets            int64                  `protobuf:"varint,3,opt,name=rxPackets,proto3" json:"rxPackets,omitempty"`
	TxPackets            int64                  `protobuf:"varint,4,opt,name=txPackets,proto3" json:"txPackets,omitempty"`
	RxBps                int64                  `protobuf:"varint,5,opt,name=rxBps,proto3" json:"rxBps,omitempty"`
	TxBps                int64                  `protobuf:"varint,6,opt,name=txBps,proto3" json:"txBps,omitempty"`
	RxPps                int64                  `protobuf:"varint,7,opt,name=rxPps,proto3" json:"rxPps,omitempty"`
	TxPps                int64                  `protobuf:"varint,8,opt,name=txPps,proto3" json:"txPps,omitempty"`
	RxBytesDelta         int64                  `protobuf:"varint,9,opt,name=rxBytesDelta,proto3" json:"rxBytesDelta,omitempty"`
	TxBytesDelta         int64                  `protobuf:"varint,10,opt,name=txBytesDelta,proto3" json:"txBytesDelta,omitempty"`
	RxPacketsDelta       int64                  `protobuf:"varint,11,opt,name=rxPacketsDelta,proto3" json:"rxPacketsDelta,omitempty"`
	TxPacketsDelta       int64                  `protobuf:"varint,12,opt,name=txPacketsDelta,proto3" json:"txPacketsDelta,omitempty"`
	TxDropDataFrameDelta int64                  `protobuf:"varint,13,opt,name=txDropDataFrameDelta,proto3" json:"txDropDataFrameDelta,omitempty"`
	RxCRCErrFramesDelta  int64                  `protobuf:"varint,14,opt,name=rxCRCErrFramesDelta,proto3" json:"rxCRCErrFramesDelta,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ClientTrafficInfo) Reset() {
	*x = ClientTrafficInfo{}
	mi := &file_wnms_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTrafficInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTrafficInfo) ProtoMessage() {}

func (x *ClientTrafficInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTrafficInfo.ProtoReflect.Descriptor instead.
func (*ClientTrafficInfo) Descriptor() ([]byte, []int) {
	return file_wnms_client_proto_rawDescGZIP(), []int{2}
}

func (x *ClientTrafficInfo) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *ClientTrafficInfo) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *ClientTrafficInfo) GetRxPackets() int64 {
	if x != nil {
		return x.RxPackets
	}
	return 0
}

func (x *ClientTrafficInfo) GetTxPackets() int64 {
	if x != nil {
		return x.TxPackets
	}
	return 0
}

func (x *ClientTrafficInfo) GetRxBps() int64 {
	if x != nil {
		return x.RxBps
	}
	return 0
}

func (x *ClientTrafficInfo) GetTxBps() int64 {
	if x != nil {
		return x.TxBps
	}
	return 0
}

func (x *ClientTrafficInfo) GetRxPps() int64 {
	if x != nil {
		return x.RxPps
	}
	return 0
}

func (x *ClientTrafficInfo) GetTxPps() int64 {
	if x != nil {
		return x.TxPps
	}
	return 0
}

func (x *ClientTrafficInfo) GetRxBytesDelta() int64 {
	if x != nil {
		return x.RxBytesDelta
	}
	return 0
}

func (x *ClientTrafficInfo) GetTxBytesDelta() int64 {
	if x != nil {
		return x.TxBytesDelta
	}
	return 0
}

func (x *ClientTrafficInfo) GetRxPacketsDelta() int64 {
	if x != nil {
		return x.RxPacketsDelta
	}
	return 0
}

func (x *ClientTrafficInfo) GetTxPacketsDelta() int64 {
	if x != nil {
		return x.TxPacketsDelta
	}
	return 0
}

func (x *ClientTrafficInfo) GetTxDropDataFrameDelta() int64 {
	if x != nil {
		return x.TxDropDataFrameDelta
	}
	return 0
}

func (x *ClientTrafficInfo) GetRxCRCErrFramesDelta() int64 {
	if x != nil {
		return x.RxCRCErrFramesDelta
	}
	return 0
}

var File_wnms_client_proto protoreflect.FileDescriptor

const file_wnms_client_proto_rawDesc = "" +
	"\n" +
	"\x11wnms_client.proto\x12\x1fkr.connectlabs.wnms.proto.model\"\xc1\x01\n" +
	"\fClientReport\x12\x14\n" +
	"\x05apMac\x18\x01 \x01(\tR\x05apMac\x12\x12\n" +
	"\x04apIp\x18\x02 \x01(\tR\x04apIp\x12K\n" +
	"\n" +
	"clientList\x18\x03 \x03(\v2+.kr.connectlabs.wnms.proto.model.ClientInfoR\n" +
	"clientList\x12\x1c\n" +
	"\tclientNum\x18\x04 \x01(\x05R\tclientNum\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xb0\v\n" +
	"\n" +
	"ClientInfo\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\tR\x03mac\x12\x1c\n" +
	"\tipAddress\x18\x02 \x01(\tR\tipAddress\x12\x1c\n" +
	"\tradioMode\x18\x03 \x01(\tR\tradioMode\x12/\n" +
	"\x10ap80211RadioMode\x18\x04 \x01(\tH\x00R\x10ap80211RadioMode\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"authMethod\x18\x05 \x01(\tR\n" +
	"authMethod\x12)\n" +
	"\rencryptMethod\x18\x06 \x01(\tH\x01R\rencryptMethod\x88\x01\x01\x12\x14\n" +
	"\x05bssid\x18\a \x01(\tR\x05bssid\x12\x12\n" +
	"\x04ssid\x18\b \x01(\tR\x04ssid\x12\x1f\n" +
	"\busername\x18\t \x01(\tH\x02R\busername\x88\x01\x01\x12\x12\n" +
	"\x04vlan\x18\n" +
	" \x01(\x05R\x04vlan\x12\x1b\n" +
	"\x06osType\x18\v \x01(\tH\x03R\x06osType\x88\x01\x01\x12\x1a\n" +
	"\bhostname\x18\f \x01(\tR\bhostname\x12\x18\n" +
	"\achannel\x18\r \x01(\x05R\achannel\x12\"\n" +
	"\fchannelWidth\x18\x0e \x01(\x05R\fchannelWidth\x12\x12\n" +
	"\x04rssi\x18\x0f \x01(\x05R\x04rssi\x12\x1d\n" +
	"\amaxRssi\x18\x10 \x01(\x05H\x04R\amaxRssi\x88\x01\x01\x12\x1d\n" +
	"\aminRssi\x18\x11 \x01(\x05H\x05R\aminRssi\x88\x01\x01\x12!\n" +
	"\tfirstRssi\x18\x12 \x01(\x05H\x06R\tfirstRssi\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"noiseFloor\x18\x13 \x01(\x05R\n" +
	"noiseFloor\x12\x10\n" +
	"\x03snr\x18\x14 \x01(\x05R\x03snr\x12\x1a\n" +
	"\blocation\x18\x15 \x01(\tR\blocation\x12\x1c\n" +
	"\tsessionId\x18\x16 \x01(\tR\tsessionId\x12'\n" +
	"\fipAssignTime\x18\x17 \x01(\x04H\aR\fipAssignTime\x88\x01\x01\x12 \n" +
	"\vsessionTime\x18\x18 \x01(\x04R\vsessionTime\x12\x18\n" +
	"\aradioId\x18\x19 \x01(\x04R\aradioId\x12!\n" +
	"\twsgWlanId\x18\x1a \x01(\x04H\bR\twsgWlanId\x88\x01\x01\x12%\n" +
	"\vwlanGroupId\x18\x1b \x01(\tH\tR\vwlanGroupId\x88\x01\x01\x12(\n" +
	"\x0fmedianTxMCSRate\x18\x1c \x01(\x04R\x0fmedianTxMCSRate\x12(\n" +
	"\x0fmedianRxMCSRate\x18\x1d \x01(\x04R\x0fmedianRxMCSRate\x12#\n" +
	"\n" +
	"deviceType\x18\x1e \x01(\x05H\n" +
	"R\n" +
	"deviceType\x88\x01\x01\x12'\n" +
	"\fosVendorType\x18\x1f \x01(\x04H\vR\fosVendorType\x88\x01\x01\x12\x14\n" +
	"\x05txPer\x18  \x01(\x04R\x05txPer\x12L\n" +
	"\atraffic\x18! \x01(\v22.kr.connectlabs.wnms.proto.model.ClientTrafficInfoR\atraffic\x12\x17\n" +
	"\x04cpIp\x183 \x01(\tH\fR\x04cpIp\x88\x01\x01\x12\x17\n" +
	"\x04dpIp\x184 \x01(\tH\rR\x04dpIp\x88\x01\x01\x12#\n" +
	"\n" +
	"mldAddress\x18G \x01(\tH\x0eR\n" +
	"mldAddress\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"regionCode\x18[ \x01(\tR\n" +
	"regionCode\x12 \n" +
	"\vfactoryCode\x18\\ \x01(\tR\vfactoryCodeB\x13\n" +
	"\x11_ap80211RadioModeB\x10\n" +
	"\x0e_encryptMethodB\v\n" +
	"\t_usernameB\t\n" +
	"\a_osTypeB\n" +
	"\n" +
	"\b_maxRssiB\n" +
	"\n" +
	"\b_minRssiB\f\n" +
	"\n" +
	"_firstRssiB\x0f\n" +
	"\r_ipAssignTimeB\f\n" +
	"\n" +
	"_wsgWlanIdB\x0e\n" +
	"\f_wlanGroupIdB\r\n" +
	"\v_deviceTypeB\x0f\n" +
	"\r_osVendorTypeB\a\n" +
	"\x05_cpIpB\a\n" +
	"\x05_dpIpB\r\n" +
	"\v_mldAddress\"\xd9\x03\n" +
	"\x11ClientTrafficInfo\x12\x18\n" +
	"\arxBytes\x18\x01 \x01(\x03R\arxBytes\x12\x18\n" +
	"\atxBytes\x18\x02 \x01(\x03R\atxBytes\x12\x1c\n" +
	"\trxPackets\x18\x03 \x01(\x03R\trxPackets\x12\x1c\n" +
	"\ttxPackets\x18\x04 \x01(\x03R\ttxPackets\x12\x14\n" +
	"\x05rxBps\x18\x05 \x01(\x03R\x05rxBps\x12\x14\n" +
	"\x05txBps\x18\x06 \x01(\x03R\x05txBps\x12\x14\n" +
	"\x05rxPps\x18\a \x01(\x03R\x05rxPps\x12\x14\n" +
	"\x05txPps\x18\b \x01(\x03R\x05txPps\x12\"\n" +
	"\frxBytesDelta\x18\t \x01(\x03R\frxBytesDelta\x12\"\n" +
	"\ftxBytesDelta\x18\n" +
	" \x01(\x03R\ftxBytesDelta\x12&\n" +
	"\x0erxPacketsDelta\x18\v \x01(\x03R\x0erxPacketsDelta\x12&\n" +
	"\x0etxPacketsDelta\x18\f \x01(\x03R\x0etxPacketsDelta\x122\n" +
	"\x14txDropDataFrameDelta\x18\r \x01(\x03R\x14txDropDataFrameDelta\x120\n" +
	"\x13rxCRCErrFramesDelta\x18\x0e \x01(\x03R\x13rxCRCErrFramesDeltaB\n" +
	"Z\b../modelb\x06proto3"

var (
	file_wnms_client_proto_rawDescOnce sync.Once
	file_wnms_client_proto_rawDescData []byte
)

func file_wnms_client_proto_rawDescGZIP() []byte {
	file_wnms_client_proto_rawDescOnce.Do(func() {
		file_wnms_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wnms_client_proto_rawDesc), len(file_wnms_client_proto_rawDesc)))
	})
	return file_wnms_client_proto_rawDescData
}

var file_wnms_client_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wnms_client_proto_goTypes = []any{
	(*ClientReport)(nil),      // 0: kr.connectlabs.wnms.proto.model.ClientReport
	(*ClientInfo)(nil),        // 1: kr.connectlabs.wnms.proto.model.ClientInfo
	(*ClientTrafficInfo)(nil), // 2: kr.connectlabs.wnms.proto.model.ClientTrafficInfo
}
var file_wnms_client_proto_depIdxs = []int32{
	1, // 0: kr.connectlabs.wnms.proto.model.ClientReport.clientList:type_name -> kr.connectlabs.wnms.proto.model.ClientInfo
	2, // 1: kr.connectlabs.wnms.proto.model.ClientInfo.traffic:type_name -> kr.connectlabs.wnms.proto.model.ClientTrafficInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wnms_client_proto_init() }
func file_wnms_client_proto_init() {
	if File_wnms_client_proto != nil {
		return
	}
	file_wnms_client_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wnms_client_proto_rawDesc), len(file_wnms_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wnms_client_proto_goTypes,
		DependencyIndexes: file_wnms_client_proto_depIdxs,
		MessageInfos:      file_wnms_client_proto_msgTypes,
	}.Build()
	File_wnms_client_proto = out.File
	file_wnms_client_proto_goTypes = nil
	file_wnms_client_proto_depIdxs = nil
}
