// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: wnms_plane.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plane struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	DeviceName    string                 `protobuf:"bytes,3,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	DeviceType    string                 `protobuf:"bytes,4,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	Role          *string                `protobuf:"bytes,5,opt,name=role,proto3,oneof" json:"role,omitempty"`
	Ipv4          *string                `protobuf:"bytes,6,opt,name=ipv4,proto3,oneof" json:"ipv4,omitempty"`
	Ipv6          *string                `protobuf:"bytes,7,opt,name=ipv6,proto3,oneof" json:"ipv6,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MacAddress    *string                `protobuf:"bytes,9,opt,name=macAddress,proto3,oneof" json:"macAddress,omitempty"`
	Model         *string                `protobuf:"bytes,10,opt,name=model,proto3,oneof" json:"model,omitempty"`
	Serial        *string                `protobuf:"bytes,11,opt,name=serial,proto3,oneof" json:"serial,omitempty"`
	Status        string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	Uptime        *int32                 `protobuf:"varint,13,opt,name=uptime,proto3,oneof" json:"uptime,omitempty"`
	UptimeStr     *string                `protobuf:"bytes,14,opt,name=uptimeStr,proto3,oneof" json:"uptimeStr,omitempty"`
	Version       string                 `protobuf:"bytes,15,opt,name=version,proto3" json:"version,omitempty"`
	ApVersion     *string                `protobuf:"bytes,16,opt,name=apVersion,proto3,oneof" json:"apVersion,omitempty"`
	Hostname      *string                `protobuf:"bytes,17,opt,name=hostname,proto3,oneof" json:"hostname,omitempty"`
	RegionCode    string                 `protobuf:"bytes,91,opt,name=regionCode,proto3" json:"regionCode,omitempty"`
	FactoryCode   string                 `protobuf:"bytes,92,opt,name=factoryCode,proto3" json:"factoryCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plane) Reset() {
	*x = Plane{}
	mi := &file_wnms_plane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plane) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plane) ProtoMessage() {}

func (x *Plane) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_plane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plane.ProtoReflect.Descriptor instead.
func (*Plane) Descriptor() ([]byte, []int) {
	return file_wnms_plane_proto_rawDescGZIP(), []int{0}
}

func (x *Plane) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plane) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Plane) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *Plane) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *Plane) GetRole() string {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return ""
}

func (x *Plane) GetIpv4() string {
	if x != nil && x.Ipv4 != nil {
		return *x.Ipv4
	}
	return ""
}

func (x *Plane) GetIpv6() string {
	if x != nil && x.Ipv6 != nil {
		return *x.Ipv6
	}
	return ""
}

func (x *Plane) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Plane) GetMacAddress() string {
	if x != nil && x.MacAddress != nil {
		return *x.MacAddress
	}
	return ""
}

func (x *Plane) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *Plane) GetSerial() string {
	if x != nil && x.Serial != nil {
		return *x.Serial
	}
	return ""
}

func (x *Plane) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Plane) GetUptime() int32 {
	if x != nil && x.Uptime != nil {
		return *x.Uptime
	}
	return 0
}

func (x *Plane) GetUptimeStr() string {
	if x != nil && x.UptimeStr != nil {
		return *x.UptimeStr
	}
	return ""
}

func (x *Plane) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Plane) GetApVersion() string {
	if x != nil && x.ApVersion != nil {
		return *x.ApVersion
	}
	return ""
}

func (x *Plane) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *Plane) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

func (x *Plane) GetFactoryCode() string {
	if x != nil {
		return x.FactoryCode
	}
	return ""
}

var File_wnms_plane_proto protoreflect.FileDescriptor

const file_wnms_plane_proto_rawDesc = "" +
	"\n" +
	"\x10wnms_plane.proto\x12\x1fkr.connectlabs.wnms.proto.model\"\xbf\x05\n" +
	"\x05Plane\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"deviceName\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x1e\n" +
	"\n" +
	"deviceType\x18\x04 \x01(\tR\n" +
	"deviceType\x12\x17\n" +
	"\x04role\x18\x05 \x01(\tH\x01R\x04role\x88\x01\x01\x12\x17\n" +
	"\x04ipv4\x18\x06 \x01(\tH\x02R\x04ipv4\x88\x01\x01\x12\x17\n" +
	"\x04ipv6\x18\a \x01(\tH\x03R\x04ipv6\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x04R\ttimestamp\x12#\n" +
	"\n" +
	"macAddress\x18\t \x01(\tH\x04R\n" +
	"macAddress\x88\x01\x01\x12\x19\n" +
	"\x05model\x18\n" +
	" \x01(\tH\x05R\x05model\x88\x01\x01\x12\x1b\n" +
	"\x06serial\x18\v \x01(\tH\x06R\x06serial\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12\x1b\n" +
	"\x06uptime\x18\r \x01(\x05H\aR\x06uptime\x88\x01\x01\x12!\n" +
	"\tuptimeStr\x18\x0e \x01(\tH\bR\tuptimeStr\x88\x01\x01\x12\x18\n" +
	"\aversion\x18\x0f \x01(\tR\aversion\x12!\n" +
	"\tapVersion\x18\x10 \x01(\tH\tR\tapVersion\x88\x01\x01\x12\x1f\n" +
	"\bhostname\x18\x11 \x01(\tH\n" +
	"R\bhostname\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"regionCode\x18[ \x01(\tR\n" +
	"regionCode\x12 \n" +
	"\vfactoryCode\x18\\ \x01(\tR\vfactoryCodeB\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_roleB\a\n" +
	"\x05_ipv4B\a\n" +
	"\x05_ipv6B\r\n" +
	"\v_macAddressB\b\n" +
	"\x06_modelB\t\n" +
	"\a_serialB\t\n" +
	"\a_uptimeB\f\n" +
	"\n" +
	"_uptimeStrB\f\n" +
	"\n" +
	"_apVersionB\v\n" +
	"\t_hostnameB\n" +
	"Z\b../modelb\x06proto3"

var (
	file_wnms_plane_proto_rawDescOnce sync.Once
	file_wnms_plane_proto_rawDescData []byte
)

func file_wnms_plane_proto_rawDescGZIP() []byte {
	file_wnms_plane_proto_rawDescOnce.Do(func() {
		file_wnms_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wnms_plane_proto_rawDesc), len(file_wnms_plane_proto_rawDesc)))
	})
	return file_wnms_plane_proto_rawDescData
}

var file_wnms_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wnms_plane_proto_goTypes = []any{
	(*Plane)(nil), // 0: kr.connectlabs.wnms.proto.model.Plane
}
var file_wnms_plane_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wnms_plane_proto_init() }
func file_wnms_plane_proto_init() {
	if File_wnms_plane_proto != nil {
		return
	}
	file_wnms_plane_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wnms_plane_proto_rawDesc), len(file_wnms_plane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wnms_plane_proto_goTypes,
		DependencyIndexes: file_wnms_plane_proto_depIdxs,
		MessageInfos:      file_wnms_plane_proto_msgTypes,
	}.Build()
	File_wnms_plane_proto = out.File
	file_wnms_plane_proto_goTypes = nil
	file_wnms_plane_proto_depIdxs = nil
}
