// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: wnms_alarm.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlarmReport_AlarmState int32

const (
	// *
	// @description OUTSTANDING
	// @since 3.5.1
	AlarmReport_OUTSTANDING AlarmReport_AlarmState = 0
	// *
	// @description CLEARED
	// @since 3.5.1
	AlarmReport_CLEARED    AlarmReport_AlarmState = 1
	AlarmReport_PROCESSING AlarmReport_AlarmState = 2
)

// Enum value maps for AlarmReport_AlarmState.
var (
	AlarmReport_AlarmState_name = map[int32]string{
		0: "OUTSTANDING",
		1: "CLEARED",
		2: "PROCESSING",
	}
	AlarmReport_AlarmState_value = map[string]int32{
		"OUTSTANDING": 0,
		"CLEARED":     1,
		"PROCESSING":  2,
	}
)

func (x AlarmReport_AlarmState) Enum() *AlarmReport_AlarmState {
	p := new(AlarmReport_AlarmState)
	*p = x
	return p
}

func (x AlarmReport_AlarmState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlarmReport_AlarmState) Descriptor() protoreflect.EnumDescriptor {
	return file_wnms_alarm_proto_enumTypes[0].Descriptor()
}

func (AlarmReport_AlarmState) Type() protoreflect.EnumType {
	return &file_wnms_alarm_proto_enumTypes[0]
}

func (x AlarmReport_AlarmState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlarmReport_AlarmState.Descriptor instead.
func (AlarmReport_AlarmState) EnumDescriptor() ([]byte, []int) {
	return file_wnms_alarm_proto_rawDescGZIP(), []int{0, 0}
}

type AlarmReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description GPB version
	// @since 3.5.1
	Version *uint32 `protobuf:"varint,1,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Alarm UUID
	// @since 3.5.1
	AlarmUuid *string `protobuf:"bytes,2,opt,name=alarmUuid,proto3,oneof" json:"alarmUuid,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Alarm Code defined by AlarmEnum
	// @since 3.5.1
	AlarmCode string `protobuf:"bytes,3,opt,name=alarmCode,proto3" json:"alarmCode,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Alarm severity defined by AlarmEnum
	// @since 3.5.1
	AlarmSeverity string `protobuf:"bytes,4,opt,name=alarmSeverity,proto3" json:"alarmSeverity,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Alarm main categorty defined by AlarmCategory
	// @since 3.5.1
	MainCategory string `protobuf:"bytes,5,opt,name=mainCategory,proto3" json:"mainCategory,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Alarm type description defined by AlarmEnum represented with String.
	// @since 3.5.1
	AlarmType *string `protobuf:"bytes,6,opt,name=alarmType,proto3,oneof" json:"alarmType,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description The triggerring event code number for this alarm.
	// @since 3.5.1
	InitEventCode *uint32 `protobuf:"varint,7,opt,name=initEventCode,proto3,oneof" json:"initEventCode,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description The timestamp of this alarm's creation.
	// @since 3.5.1
	Timestamp uint64 `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description The AlarmState of current triggering alarm which contains (OUTSTANDING/CLEARED).
	// @since 3.5.1
	AlarmState AlarmReport_AlarmState `protobuf:"varint,9,opt,name=alarmState,proto3,enum=kr.connectlabs.wnms.proto.model.AlarmReport_AlarmState" json:"alarmState,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Domain UUID.
	// @since 3.5.1
	DomainId *string `protobuf:"bytes,11,opt,name=domainId,proto3,oneof" json:"domainId,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Zone UUID. Unique zone ID assigned by SZ controller.
	// @since 3.5.1
	ZoneId *string `protobuf:"bytes,12,opt,name=zoneId,proto3,oneof" json:"zoneId,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description AP Group identifier.
	// @since 3.5.1
	ApGroupId *string `protobuf:"bytes,13,opt,name=apGroupId,proto3,oneof" json:"apGroupId,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Access Point  MAC address.
	// @since 3.5.1
	ApMac *string `protobuf:"bytes,14,opt,name=apMac,proto3,oneof" json:"apMac,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description UE/Client MAC address if the events are related to client.
	// @since 3.5.1
	ClientMac *string `protobuf:"bytes,15,opt,name=clientMac,proto3,oneof" json:"clientMac,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Reason for the alarm to occur.
	// @since 3.5.1
	Reason *string `protobuf:"bytes,16,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Domain name.
	// @since 3.5.1
	DomainName *string `protobuf:"bytes,17,opt,name=domainName,proto3,oneof" json:"domainName,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Zone name assigned by the controller. The admin configures the Zone name via the contoller's user interface.
	// @since 3.5.1
	ZoneName *string `protobuf:"bytes,18,opt,name=zoneName,proto3,oneof" json:"zoneName,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description AP Group name.
	// @since 3.5.1
	ApGroupName *string `protobuf:"bytes,19,opt,name=apGroupName,proto3,oneof" json:"apGroupName,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description IPv4 address of the AP.
	// @since 3.5.1
	ApIpAddress *string `protobuf:"bytes,20,opt,name=apIpAddress,proto3,oneof" json:"apIpAddress,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description IPv6 address of the AP.
	// @since 3.5.1
	ApIpv6Address *string `protobuf:"bytes,21,opt,name=apIpv6Address,proto3,oneof" json:"apIpv6Address,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Description of the alarm represented by string.
	// @since 3.5.1
	Description string `protobuf:"bytes,22,opt,name=description,proto3" json:"description,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Sub category of the alarm.
	// @since 3.5.1
	SubCategory *string `protobuf:"bytes,23,opt,name=subCategory,proto3,oneof" json:"subCategory,omitempty"`
	// *
	// @property snapshot
	// @aggregation NULL
	// @description Blade ID information from which node alarm created.
	// @since 3.5.1
	BladeId       *string `protobuf:"bytes,24,opt,name=bladeId,proto3,oneof" json:"bladeId,omitempty"`
	Vendor        string  `protobuf:"bytes,41,opt,name=vendor,proto3" json:"vendor,omitempty"`
	NetworkType   string  `protobuf:"bytes,42,opt,name=networkType,proto3" json:"networkType,omitempty"`
	RegionCode    string  `protobuf:"bytes,91,opt,name=regionCode,proto3" json:"regionCode,omitempty"`
	FactoryCode   string  `protobuf:"bytes,92,opt,name=factoryCode,proto3" json:"factoryCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmReport) Reset() {
	*x = AlarmReport{}
	mi := &file_wnms_alarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmReport) ProtoMessage() {}

func (x *AlarmReport) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_alarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmReport.ProtoReflect.Descriptor instead.
func (*AlarmReport) Descriptor() ([]byte, []int) {
	return file_wnms_alarm_proto_rawDescGZIP(), []int{0}
}

func (x *AlarmReport) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *AlarmReport) GetAlarmUuid() string {
	if x != nil && x.AlarmUuid != nil {
		return *x.AlarmUuid
	}
	return ""
}

func (x *AlarmReport) GetAlarmCode() string {
	if x != nil {
		return x.AlarmCode
	}
	return ""
}

func (x *AlarmReport) GetAlarmSeverity() string {
	if x != nil {
		return x.AlarmSeverity
	}
	return ""
}

func (x *AlarmReport) GetMainCategory() string {
	if x != nil {
		return x.MainCategory
	}
	return ""
}

func (x *AlarmReport) GetAlarmType() string {
	if x != nil && x.AlarmType != nil {
		return *x.AlarmType
	}
	return ""
}

func (x *AlarmReport) GetInitEventCode() uint32 {
	if x != nil && x.InitEventCode != nil {
		return *x.InitEventCode
	}
	return 0
}

func (x *AlarmReport) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AlarmReport) GetAlarmState() AlarmReport_AlarmState {
	if x != nil {
		return x.AlarmState
	}
	return AlarmReport_OUTSTANDING
}

func (x *AlarmReport) GetDomainId() string {
	if x != nil && x.DomainId != nil {
		return *x.DomainId
	}
	return ""
}

func (x *AlarmReport) GetZoneId() string {
	if x != nil && x.ZoneId != nil {
		return *x.ZoneId
	}
	return ""
}

func (x *AlarmReport) GetApGroupId() string {
	if x != nil && x.ApGroupId != nil {
		return *x.ApGroupId
	}
	return ""
}

func (x *AlarmReport) GetApMac() string {
	if x != nil && x.ApMac != nil {
		return *x.ApMac
	}
	return ""
}

func (x *AlarmReport) GetClientMac() string {
	if x != nil && x.ClientMac != nil {
		return *x.ClientMac
	}
	return ""
}

func (x *AlarmReport) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *AlarmReport) GetDomainName() string {
	if x != nil && x.DomainName != nil {
		return *x.DomainName
	}
	return ""
}

func (x *AlarmReport) GetZoneName() string {
	if x != nil && x.ZoneName != nil {
		return *x.ZoneName
	}
	return ""
}

func (x *AlarmReport) GetApGroupName() string {
	if x != nil && x.ApGroupName != nil {
		return *x.ApGroupName
	}
	return ""
}

func (x *AlarmReport) GetApIpAddress() string {
	if x != nil && x.ApIpAddress != nil {
		return *x.ApIpAddress
	}
	return ""
}

func (x *AlarmReport) GetApIpv6Address() string {
	if x != nil && x.ApIpv6Address != nil {
		return *x.ApIpv6Address
	}
	return ""
}

func (x *AlarmReport) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AlarmReport) GetSubCategory() string {
	if x != nil && x.SubCategory != nil {
		return *x.SubCategory
	}
	return ""
}

func (x *AlarmReport) GetBladeId() string {
	if x != nil && x.BladeId != nil {
		return *x.BladeId
	}
	return ""
}

func (x *AlarmReport) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *AlarmReport) GetNetworkType() string {
	if x != nil {
		return x.NetworkType
	}
	return ""
}

func (x *AlarmReport) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

func (x *AlarmReport) GetFactoryCode() string {
	if x != nil {
		return x.FactoryCode
	}
	return ""
}

var File_wnms_alarm_proto protoreflect.FileDescriptor

const file_wnms_alarm_proto_rawDesc = "" +
	"\n" +
	"\x10wnms_alarm.proto\x12\x1fkr.connectlabs.wnms.proto.model\"\x84\n" +
	"\n" +
	"\vAlarmReport\x12\x1d\n" +
	"\aversion\x18\x01 \x01(\rH\x00R\aversion\x88\x01\x01\x12!\n" +
	"\talarmUuid\x18\x02 \x01(\tH\x01R\talarmUuid\x88\x01\x01\x12\x1c\n" +
	"\talarmCode\x18\x03 \x01(\tR\talarmCode\x12$\n" +
	"\ralarmSeverity\x18\x04 \x01(\tR\ralarmSeverity\x12\"\n" +
	"\fmainCategory\x18\x05 \x01(\tR\fmainCategory\x12!\n" +
	"\talarmType\x18\x06 \x01(\tH\x02R\talarmType\x88\x01\x01\x12)\n" +
	"\rinitEventCode\x18\a \x01(\rH\x03R\rinitEventCode\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x04R\ttimestamp\x12W\n" +
	"\n" +
	"alarmState\x18\t \x01(\x0e27.kr.connectlabs.wnms.proto.model.AlarmReport.AlarmStateR\n" +
	"alarmState\x12\x1f\n" +
	"\bdomainId\x18\v \x01(\tH\x04R\bdomainId\x88\x01\x01\x12\x1b\n" +
	"\x06zoneId\x18\f \x01(\tH\x05R\x06zoneId\x88\x01\x01\x12!\n" +
	"\tapGroupId\x18\r \x01(\tH\x06R\tapGroupId\x88\x01\x01\x12\x19\n" +
	"\x05apMac\x18\x0e \x01(\tH\aR\x05apMac\x88\x01\x01\x12!\n" +
	"\tclientMac\x18\x0f \x01(\tH\bR\tclientMac\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\x10 \x01(\tH\tR\x06reason\x88\x01\x01\x12#\n" +
	"\n" +
	"domainName\x18\x11 \x01(\tH\n" +
	"R\n" +
	"domainName\x88\x01\x01\x12\x1f\n" +
	"\bzoneName\x18\x12 \x01(\tH\vR\bzoneName\x88\x01\x01\x12%\n" +
	"\vapGroupName\x18\x13 \x01(\tH\fR\vapGroupName\x88\x01\x01\x12%\n" +
	"\vapIpAddress\x18\x14 \x01(\tH\rR\vapIpAddress\x88\x01\x01\x12)\n" +
	"\rapIpv6Address\x18\x15 \x01(\tH\x0eR\rapIpv6Address\x88\x01\x01\x12 \n" +
	"\vdescription\x18\x16 \x01(\tR\vdescription\x12%\n" +
	"\vsubCategory\x18\x17 \x01(\tH\x0fR\vsubCategory\x88\x01\x01\x12\x1d\n" +
	"\abladeId\x18\x18 \x01(\tH\x10R\abladeId\x88\x01\x01\x12\x16\n" +
	"\x06vendor\x18) \x01(\tR\x06vendor\x12 \n" +
	"\vnetworkType\x18* \x01(\tR\vnetworkType\x12\x1e\n" +
	"\n" +
	"regionCode\x18[ \x01(\tR\n" +
	"regionCode\x12 \n" +
	"\vfactoryCode\x18\\ \x01(\tR\vfactoryCode\":\n" +
	"\n" +
	"AlarmState\x12\x0f\n" +
	"\vOUTSTANDING\x10\x00\x12\v\n" +
	"\aCLEARED\x10\x01\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x02B\n" +
	"\n" +
	"\b_versionB\f\n" +
	"\n" +
	"_alarmUuidB\f\n" +
	"\n" +
	"_alarmTypeB\x10\n" +
	"\x0e_initEventCodeB\v\n" +
	"\t_domainIdB\t\n" +
	"\a_zoneIdB\f\n" +
	"\n" +
	"_apGroupIdB\b\n" +
	"\x06_apMacB\f\n" +
	"\n" +
	"_clientMacB\t\n" +
	"\a_reasonB\r\n" +
	"\v_domainNameB\v\n" +
	"\t_zoneNameB\x0e\n" +
	"\f_apGroupNameB\x0e\n" +
	"\f_apIpAddressB\x10\n" +
	"\x0e_apIpv6AddressB\x0e\n" +
	"\f_subCategoryB\n" +
	"\n" +
	"\b_bladeIdB\n" +
	"Z\b../modelb\x06proto3"

var (
	file_wnms_alarm_proto_rawDescOnce sync.Once
	file_wnms_alarm_proto_rawDescData []byte
)

func file_wnms_alarm_proto_rawDescGZIP() []byte {
	file_wnms_alarm_proto_rawDescOnce.Do(func() {
		file_wnms_alarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wnms_alarm_proto_rawDesc), len(file_wnms_alarm_proto_rawDesc)))
	})
	return file_wnms_alarm_proto_rawDescData
}

var file_wnms_alarm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wnms_alarm_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wnms_alarm_proto_goTypes = []any{
	(AlarmReport_AlarmState)(0), // 0: kr.connectlabs.wnms.proto.model.AlarmReport.AlarmState
	(*AlarmReport)(nil),         // 1: kr.connectlabs.wnms.proto.model.AlarmReport
}
var file_wnms_alarm_proto_depIdxs = []int32{
	0, // 0: kr.connectlabs.wnms.proto.model.AlarmReport.alarmState:type_name -> kr.connectlabs.wnms.proto.model.AlarmReport.AlarmState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wnms_alarm_proto_init() }
func file_wnms_alarm_proto_init() {
	if File_wnms_alarm_proto != nil {
		return
	}
	file_wnms_alarm_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wnms_alarm_proto_rawDesc), len(file_wnms_alarm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wnms_alarm_proto_goTypes,
		DependencyIndexes: file_wnms_alarm_proto_depIdxs,
		EnumInfos:         file_wnms_alarm_proto_enumTypes,
		MessageInfos:      file_wnms_alarm_proto_msgTypes,
	}.Build()
	File_wnms_alarm_proto = out.File
	file_wnms_alarm_proto_goTypes = nil
	file_wnms_alarm_proto_depIdxs = nil
}
