// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: wnms_message.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ReturnCode    int32                  `protobuf:"varint,2,opt,name=returnCode,proto3" json:"returnCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcReply) Reset() {
	*x = RpcReply{}
	mi := &file_wnms_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcReply) ProtoMessage() {}

func (x *RpcReply) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcReply.ProtoReflect.Descriptor instead.
func (*RpcReply) Descriptor() ([]byte, []int) {
	return file_wnms_message_proto_rawDescGZIP(), []int{0}
}

func (x *RpcReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RpcReply) GetReturnCode() int32 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

type RpcRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Message          string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp        int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ApReport         *ApReport              `protobuf:"bytes,11,opt,name=apReport,proto3" json:"apReport,omitempty"`
	ClientReport     *ClientReport          `protobuf:"bytes,12,opt,name=clientReport,proto3" json:"clientReport,omitempty"`
	EventReport      *EventReport           `protobuf:"bytes,21,opt,name=eventReport,proto3" json:"eventReport,omitempty"`
	AlarmReport      *AlarmReport           `protobuf:"bytes,22,opt,name=alarmReport,proto3" json:"alarmReport,omitempty"`
	PlaneReport      *Plane                 `protobuf:"bytes,31,opt,name=planeReport,proto3" json:"planeReport,omitempty"`
	P5GStatsReport   *P5GStatsReport        `protobuf:"bytes,41,opt,name=p5gStatsReport,proto3" json:"p5gStatsReport,omitempty"`
	P5GUeStatsReport *P5GUeStatsReport      `protobuf:"bytes,42,opt,name=p5gUeStatsReport,proto3" json:"p5gUeStatsReport,omitempty"`
	StatisticsReport *StatisticsReport      `protobuf:"bytes,51,opt,name=statisticsReport,proto3" json:"statisticsReport,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	mi := &file_wnms_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_wnms_message_proto_rawDescGZIP(), []int{1}
}

func (x *RpcRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RpcRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RpcRequest) GetApReport() *ApReport {
	if x != nil {
		return x.ApReport
	}
	return nil
}

func (x *RpcRequest) GetClientReport() *ClientReport {
	if x != nil {
		return x.ClientReport
	}
	return nil
}

func (x *RpcRequest) GetEventReport() *EventReport {
	if x != nil {
		return x.EventReport
	}
	return nil
}

func (x *RpcRequest) GetAlarmReport() *AlarmReport {
	if x != nil {
		return x.AlarmReport
	}
	return nil
}

func (x *RpcRequest) GetPlaneReport() *Plane {
	if x != nil {
		return x.PlaneReport
	}
	return nil
}

func (x *RpcRequest) GetP5GStatsReport() *P5GStatsReport {
	if x != nil {
		return x.P5GStatsReport
	}
	return nil
}

func (x *RpcRequest) GetP5GUeStatsReport() *P5GUeStatsReport {
	if x != nil {
		return x.P5GUeStatsReport
	}
	return nil
}

func (x *RpcRequest) GetStatisticsReport() *StatisticsReport {
	if x != nil {
		return x.StatisticsReport
	}
	return nil
}

var File_wnms_message_proto protoreflect.FileDescriptor

const file_wnms_message_proto_rawDesc = "" +
	"\n" +
	"\x12wnms_message.proto\x12\x1fkr.connectlabs.wnms.proto.model\x1a\rwnms_ap.proto\x1a\x11wnms_client.proto\x1a\x10wnms_event.proto\x1a\x10wnms_alarm.proto\x1a\x10wnms_plane.proto\x1a\x0ewnms_p5g.proto\x1a\x11wnms_p5g_ue.proto\x1a\x15wnms_statistics.proto\"D\n" +
	"\bRpcReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"returnCode\x18\x02 \x01(\x05R\n" +
	"returnCode\"\xdf\x05\n" +
	"\n" +
	"RpcRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12E\n" +
	"\bapReport\x18\v \x01(\v2).kr.connectlabs.wnms.proto.model.ApReportR\bapReport\x12Q\n" +
	"\fclientReport\x18\f \x01(\v2-.kr.connectlabs.wnms.proto.model.ClientReportR\fclientReport\x12N\n" +
	"\veventReport\x18\x15 \x01(\v2,.kr.connectlabs.wnms.proto.model.EventReportR\veventReport\x12N\n" +
	"\valarmReport\x18\x16 \x01(\v2,.kr.connectlabs.wnms.proto.model.AlarmReportR\valarmReport\x12H\n" +
	"\vplaneReport\x18\x1f \x01(\v2&.kr.connectlabs.wnms.proto.model.PlaneR\vplaneReport\x12W\n" +
	"\x0ep5gStatsReport\x18) \x01(\v2/.kr.connectlabs.wnms.proto.model.P5gStatsReportR\x0ep5gStatsReport\x12]\n" +
	"\x10p5gUeStatsReport\x18* \x01(\v21.kr.connectlabs.wnms.proto.model.P5gUeStatsReportR\x10p5gUeStatsReport\x12]\n" +
	"\x10statisticsReport\x183 \x01(\v21.kr.connectlabs.wnms.proto.model.StatisticsReportR\x10statisticsReportB\n" +
	"Z\b../modelb\x06proto3"

var (
	file_wnms_message_proto_rawDescOnce sync.Once
	file_wnms_message_proto_rawDescData []byte
)

func file_wnms_message_proto_rawDescGZIP() []byte {
	file_wnms_message_proto_rawDescOnce.Do(func() {
		file_wnms_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wnms_message_proto_rawDesc), len(file_wnms_message_proto_rawDesc)))
	})
	return file_wnms_message_proto_rawDescData
}

var file_wnms_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wnms_message_proto_goTypes = []any{
	(*RpcReply)(nil),         // 0: kr.connectlabs.wnms.proto.model.RpcReply
	(*RpcRequest)(nil),       // 1: kr.connectlabs.wnms.proto.model.RpcRequest
	(*ApReport)(nil),         // 2: kr.connectlabs.wnms.proto.model.ApReport
	(*ClientReport)(nil),     // 3: kr.connectlabs.wnms.proto.model.ClientReport
	(*EventReport)(nil),      // 4: kr.connectlabs.wnms.proto.model.EventReport
	(*AlarmReport)(nil),      // 5: kr.connectlabs.wnms.proto.model.AlarmReport
	(*Plane)(nil),            // 6: kr.connectlabs.wnms.proto.model.Plane
	(*P5GStatsReport)(nil),   // 7: kr.connectlabs.wnms.proto.model.P5gStatsReport
	(*P5GUeStatsReport)(nil), // 8: kr.connectlabs.wnms.proto.model.P5gUeStatsReport
	(*StatisticsReport)(nil), // 9: kr.connectlabs.wnms.proto.model.StatisticsReport
}
var file_wnms_message_proto_depIdxs = []int32{
	2, // 0: kr.connectlabs.wnms.proto.model.RpcRequest.apReport:type_name -> kr.connectlabs.wnms.proto.model.ApReport
	3, // 1: kr.connectlabs.wnms.proto.model.RpcRequest.clientReport:type_name -> kr.connectlabs.wnms.proto.model.ClientReport
	4, // 2: kr.connectlabs.wnms.proto.model.RpcRequest.eventReport:type_name -> kr.connectlabs.wnms.proto.model.EventReport
	5, // 3: kr.connectlabs.wnms.proto.model.RpcRequest.alarmReport:type_name -> kr.connectlabs.wnms.proto.model.AlarmReport
	6, // 4: kr.connectlabs.wnms.proto.model.RpcRequest.planeReport:type_name -> kr.connectlabs.wnms.proto.model.Plane
	7, // 5: kr.connectlabs.wnms.proto.model.RpcRequest.p5gStatsReport:type_name -> kr.connectlabs.wnms.proto.model.P5gStatsReport
	8, // 6: kr.connectlabs.wnms.proto.model.RpcRequest.p5gUeStatsReport:type_name -> kr.connectlabs.wnms.proto.model.P5gUeStatsReport
	9, // 7: kr.connectlabs.wnms.proto.model.RpcRequest.statisticsReport:type_name -> kr.connectlabs.wnms.proto.model.StatisticsReport
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_wnms_message_proto_init() }
func file_wnms_message_proto_init() {
	if File_wnms_message_proto != nil {
		return
	}
	file_wnms_ap_proto_init()
	file_wnms_client_proto_init()
	file_wnms_event_proto_init()
	file_wnms_alarm_proto_init()
	file_wnms_plane_proto_init()
	file_wnms_p5g_proto_init()
	file_wnms_p5g_ue_proto_init()
	file_wnms_statistics_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wnms_message_proto_rawDesc), len(file_wnms_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wnms_message_proto_goTypes,
		DependencyIndexes: file_wnms_message_proto_depIdxs,
		MessageInfos:      file_wnms_message_proto_msgTypes,
	}.Build()
	File_wnms_message_proto = out.File
	file_wnms_message_proto_goTypes = nil
	file_wnms_message_proto_depIdxs = nil
}
