// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: wnms_p5g.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type P5GStatsReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	P5GStats  []*P5GStats `protobuf:"bytes,1,rep,name=p5gStats,proto3" json:"p5gStats,omitempty"`
	Timestamp uint64      `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *P5GStatsReport) Reset() {
	*x = P5GStatsReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wnms_p5g_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *P5GStatsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P5GStatsReport) ProtoMessage() {}

func (x *P5GStatsReport) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_p5g_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P5GStatsReport.ProtoReflect.Descriptor instead.
func (*P5GStatsReport) Descriptor() ([]byte, []int) {
	return file_wnms_p5g_proto_rawDescGZIP(), []int{0}
}

func (x *P5GStatsReport) GetP5GStats() []*P5GStats {
	if x != nil {
		return x.P5GStats
	}
	return nil
}

func (x *P5GStatsReport) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type P5GStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data map[string]string `protobuf:"bytes,10,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *P5GStats) Reset() {
	*x = P5GStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wnms_p5g_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *P5GStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P5GStats) ProtoMessage() {}

func (x *P5GStats) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_p5g_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P5GStats.ProtoReflect.Descriptor instead.
func (*P5GStats) Descriptor() ([]byte, []int) {
	return file_wnms_p5g_proto_rawDescGZIP(), []int{1}
}

func (x *P5GStats) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *P5GStats) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_wnms_p5g_proto protoreflect.FileDescriptor

var file_wnms_p5g_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x6e, 0x6d, 0x73, 0x5f, 0x70, 0x35, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1f, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x69, 0x73, 0x6b, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e,
	0x61, 0x77, 0x6e, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x22, 0x75, 0x0a, 0x0e, 0x50, 0x35, 0x67, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x45, 0x0a, 0x08, 0x70, 0x35, 0x67, 0x53, 0x74, 0x61, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x69, 0x73, 0x6b,
	0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x61, 0x77, 0x6e, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x35, 0x67, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x08, 0x70, 0x35, 0x67, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x9c, 0x01, 0x0a, 0x08, 0x50, 0x35, 0x67,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x47, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x69, 0x73, 0x6b, 0x69, 0x74,
	0x6c, 0x61, 0x62, 0x2e, 0x61, 0x77, 0x6e, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x35, 0x67, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x37,
	0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wnms_p5g_proto_rawDescOnce sync.Once
	file_wnms_p5g_proto_rawDescData = file_wnms_p5g_proto_rawDesc
)

func file_wnms_p5g_proto_rawDescGZIP() []byte {
	file_wnms_p5g_proto_rawDescOnce.Do(func() {
		file_wnms_p5g_proto_rawDescData = protoimpl.X.CompressGZIP(file_wnms_p5g_proto_rawDescData)
	})
	return file_wnms_p5g_proto_rawDescData
}

var file_wnms_p5g_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wnms_p5g_proto_goTypes = []interface{}{
	(*P5GStatsReport)(nil), // 0: com.biskitlab.awnms.proto.model.P5gStatsReport
	(*P5GStats)(nil),       // 1: com.biskitlab.awnms.proto.model.P5gStats
	nil,                    // 2: com.biskitlab.awnms.proto.model.P5gStats.DataEntry
}
var file_wnms_p5g_proto_depIdxs = []int32{
	1, // 0: com.biskitlab.awnms.proto.model.P5gStatsReport.p5gStats:type_name -> com.biskitlab.awnms.proto.model.P5gStats
	2, // 1: com.biskitlab.awnms.proto.model.P5gStats.data:type_name -> com.biskitlab.awnms.proto.model.P5gStats.DataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wnms_p5g_proto_init() }
func file_wnms_p5g_proto_init() {
	if File_wnms_p5g_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wnms_p5g_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*P5GStatsReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wnms_p5g_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*P5GStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wnms_p5g_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wnms_p5g_proto_goTypes,
		DependencyIndexes: file_wnms_p5g_proto_depIdxs,
		MessageInfos:      file_wnms_p5g_proto_msgTypes,
	}.Build()
	File_wnms_p5g_proto = out.File
	file_wnms_p5g_proto_rawDesc = nil
	file_wnms_p5g_proto_goTypes = nil
	file_wnms_p5g_proto_depIdxs = nil
}
