// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: wnms_collector_service.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_wnms_collector_service_proto protoreflect.FileDescriptor

const file_wnms_collector_service_proto_rawDesc = "" +
	"\n" +
	"\x1cwnms_collector_service.proto\x12\x1fkr.connectlabs.wnms.proto.model\x1a\x12wnms_message.proto2\xe3\b\n" +
	"\x11WnmsDataCollector\x12q\n" +
	"\x15UpdateAccessPointData\x12+.kr.connectlabs.wnms.proto.model.RpcRequest\x1a).kr.connectlabs.wnms.proto.model.RpcReply\"\x00\x12l\n" +
	"\x10UpdateClientData\x12+.kr.connectlabs.wnms.proto.model.RpcRequest\x1a).kr.connectlabs.wnms.proto.model.RpcReply\"\x00\x12k\n" +
	"\x0fUpdateEventData\x12+.kr.connectlabs.wnms.proto.model.RpcRequest\x1a).kr.connectlabs.wnms.proto.model.RpcReply\"\x00\x12k\n" +
	"\x0fUpdateAlarmData\x12+.kr.connectlabs.wnms.proto.model.RpcRequest\x1a).kr.connectlabs.wnms.proto.model.RpcReply\"\x00\x12l\n" +
	"\x10UpdateConfigData\x12+.kr.connectlabs.wnms.proto.model.RpcRequest\x1a).kr.connectlabs.wnms.proto.model.RpcReply\"\x00\x12k\n" +
	"\x0fUpdatePlaneData\x12+.kr.connectlabs.wnms.proto.model.RpcRequest\x1a).kr.connectlabs.wnms.proto.model.RpcReply\"\x00\x12d\n" +
	"\bPingData\x12+.kr.connectlabs.wnms.proto.model.RpcRequest\x1a).kr.connectlabs.wnms.proto.model.RpcReply\"\x00\x12n\n" +
	"\x12UpdateP5gStatsData\x12+.kr.connectlabs.wnms.proto.model.RpcRequest\x1a).kr.connectlabs.wnms.proto.model.RpcReply\"\x00\x12p\n" +
	"\x14UpdateP5gUeStatsData\x12+.kr.connectlabs.wnms.proto.model.RpcRequest\x1a).kr.connectlabs.wnms.proto.model.RpcReply\"\x00\x12p\n" +
	"\x14UpdateStatisticsData\x12+.kr.connectlabs.wnms.proto.model.RpcRequest\x1a).kr.connectlabs.wnms.proto.model.RpcReply\"\x00BB\n" +
	"\x19kr.connectlabs.wnms.protoB\x19WnmsCollectorServiceProtoP\x01Z\b../modelb\x06proto3"

var file_wnms_collector_service_proto_goTypes = []any{
	(*RpcRequest)(nil), // 0: kr.connectlabs.wnms.proto.model.RpcRequest
	(*RpcReply)(nil),   // 1: kr.connectlabs.wnms.proto.model.RpcReply
}
var file_wnms_collector_service_proto_depIdxs = []int32{
	0,  // 0: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdateAccessPointData:input_type -> kr.connectlabs.wnms.proto.model.RpcRequest
	0,  // 1: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdateClientData:input_type -> kr.connectlabs.wnms.proto.model.RpcRequest
	0,  // 2: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdateEventData:input_type -> kr.connectlabs.wnms.proto.model.RpcRequest
	0,  // 3: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdateAlarmData:input_type -> kr.connectlabs.wnms.proto.model.RpcRequest
	0,  // 4: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdateConfigData:input_type -> kr.connectlabs.wnms.proto.model.RpcRequest
	0,  // 5: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdatePlaneData:input_type -> kr.connectlabs.wnms.proto.model.RpcRequest
	0,  // 6: kr.connectlabs.wnms.proto.model.WnmsDataCollector.PingData:input_type -> kr.connectlabs.wnms.proto.model.RpcRequest
	0,  // 7: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdateP5gStatsData:input_type -> kr.connectlabs.wnms.proto.model.RpcRequest
	0,  // 8: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdateP5gUeStatsData:input_type -> kr.connectlabs.wnms.proto.model.RpcRequest
	0,  // 9: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdateStatisticsData:input_type -> kr.connectlabs.wnms.proto.model.RpcRequest
	1,  // 10: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdateAccessPointData:output_type -> kr.connectlabs.wnms.proto.model.RpcReply
	1,  // 11: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdateClientData:output_type -> kr.connectlabs.wnms.proto.model.RpcReply
	1,  // 12: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdateEventData:output_type -> kr.connectlabs.wnms.proto.model.RpcReply
	1,  // 13: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdateAlarmData:output_type -> kr.connectlabs.wnms.proto.model.RpcReply
	1,  // 14: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdateConfigData:output_type -> kr.connectlabs.wnms.proto.model.RpcReply
	1,  // 15: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdatePlaneData:output_type -> kr.connectlabs.wnms.proto.model.RpcReply
	1,  // 16: kr.connectlabs.wnms.proto.model.WnmsDataCollector.PingData:output_type -> kr.connectlabs.wnms.proto.model.RpcReply
	1,  // 17: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdateP5gStatsData:output_type -> kr.connectlabs.wnms.proto.model.RpcReply
	1,  // 18: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdateP5gUeStatsData:output_type -> kr.connectlabs.wnms.proto.model.RpcReply
	1,  // 19: kr.connectlabs.wnms.proto.model.WnmsDataCollector.UpdateStatisticsData:output_type -> kr.connectlabs.wnms.proto.model.RpcReply
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_wnms_collector_service_proto_init() }
func file_wnms_collector_service_proto_init() {
	if File_wnms_collector_service_proto != nil {
		return
	}
	file_wnms_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wnms_collector_service_proto_rawDesc), len(file_wnms_collector_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wnms_collector_service_proto_goTypes,
		DependencyIndexes: file_wnms_collector_service_proto_depIdxs,
	}.Build()
	File_wnms_collector_service_proto = out.File
	file_wnms_collector_service_proto_goTypes = nil
	file_wnms_collector_service_proto_depIdxs = nil
}
