// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: wnms_ap.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApList        []*ApInfo              `protobuf:"bytes,3,rep,name=apList,proto3" json:"apList,omitempty"`
	ApNum         int32                  `protobuf:"varint,4,opt,name=ApNum,proto3" json:"ApNum,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApReport) Reset() {
	*x = ApReport{}
	mi := &file_wnms_ap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApReport) ProtoMessage() {}

func (x *ApReport) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_ap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApReport.ProtoReflect.Descriptor instead.
func (*ApReport) Descriptor() ([]byte, []int) {
	return file_wnms_ap_proto_rawDescGZIP(), []int{0}
}

func (x *ApReport) GetApList() []*ApInfo {
	if x != nil {
		return x.ApList
	}
	return nil
}

func (x *ApReport) GetApNum() int32 {
	if x != nil {
		return x.ApNum
	}
	return 0
}

func (x *ApReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ApInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           string                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,3,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ControllerIp  string                 `protobuf:"bytes,5,opt,name=controllerIp,proto3" json:"controllerIp,omitempty"`
	DpIp          string                 `protobuf:"bytes,6,opt,name=dpIp,proto3" json:"dpIp,omitempty"`
	LastBootTs    uint64                 `protobuf:"varint,7,opt,name=lastBootTs,proto3" json:"lastBootTs,omitempty"`
	ApState       string                 `protobuf:"bytes,8,opt,name=apState,proto3" json:"apState,omitempty"`
	ClientNum     int32                  `protobuf:"varint,9,opt,name=clientNum,proto3" json:"clientNum,omitempty"`
	Vendor        string                 `protobuf:"bytes,10,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model         string                 `protobuf:"bytes,11,opt,name=model,proto3" json:"model,omitempty"`
	Hw            *HardwareInfo          `protobuf:"bytes,21,opt,name=hw,proto3" json:"hw,omitempty"`
	Traffic       *ApTrafficInfo         `protobuf:"bytes,22,opt,name=traffic,proto3" json:"traffic,omitempty"`
	Radio         []*RadioInfo           `protobuf:"bytes,23,rep,name=radio,proto3" json:"radio,omitempty"`
	RegionCode    string                 `protobuf:"bytes,91,opt,name=regionCode,proto3" json:"regionCode,omitempty"`
	FactoryCode   string                 `protobuf:"bytes,92,opt,name=factoryCode,proto3" json:"factoryCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApInfo) Reset() {
	*x = ApInfo{}
	mi := &file_wnms_ap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApInfo) ProtoMessage() {}

func (x *ApInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_ap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApInfo.ProtoReflect.Descriptor instead.
func (*ApInfo) Descriptor() ([]byte, []int) {
	return file_wnms_ap_proto_rawDescGZIP(), []int{1}
}

func (x *ApInfo) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *ApInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ApInfo) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *ApInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApInfo) GetControllerIp() string {
	if x != nil {
		return x.ControllerIp
	}
	return ""
}

func (x *ApInfo) GetDpIp() string {
	if x != nil {
		return x.DpIp
	}
	return ""
}

func (x *ApInfo) GetLastBootTs() uint64 {
	if x != nil {
		return x.LastBootTs
	}
	return 0
}

func (x *ApInfo) GetApState() string {
	if x != nil {
		return x.ApState
	}
	return ""
}

func (x *ApInfo) GetClientNum() int32 {
	if x != nil {
		return x.ClientNum
	}
	return 0
}

func (x *ApInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *ApInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ApInfo) GetHw() *HardwareInfo {
	if x != nil {
		return x.Hw
	}
	return nil
}

func (x *ApInfo) GetTraffic() *ApTrafficInfo {
	if x != nil {
		return x.Traffic
	}
	return nil
}

func (x *ApInfo) GetRadio() []*RadioInfo {
	if x != nil {
		return x.Radio
	}
	return nil
}

func (x *ApInfo) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

func (x *ApInfo) GetFactoryCode() string {
	if x != nil {
		return x.FactoryCode
	}
	return ""
}

type RadioInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Enabled           bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ClientNum         int32                  `protobuf:"varint,2,opt,name=clientNum,proto3" json:"clientNum,omitempty"`
	ConnFailCnt       int32                  `protobuf:"varint,3,opt,name=connFailCnt,proto3" json:"connFailCnt,omitempty"`
	FailureRate       *float32               `protobuf:"fixed32,4,opt,name=failureRate,proto3,oneof" json:"failureRate,omitempty"`
	MeshEnabled       int32                  `protobuf:"varint,5,opt,name=meshEnabled,proto3" json:"meshEnabled,omitempty"`
	IsRadioEnabled    bool                   `protobuf:"varint,6,opt,name=isRadioEnabled,proto3" json:"isRadioEnabled,omitempty"`
	Channel           int32                  `protobuf:"varint,11,opt,name=channel,proto3" json:"channel,omitempty"`
	Band              string                 `protobuf:"bytes,12,opt,name=band,proto3" json:"band,omitempty"`
	ChannelWidth      uint32                 `protobuf:"varint,13,opt,name=channelWidth,proto3" json:"channelWidth,omitempty"`
	TxPower           string                 `protobuf:"bytes,14,opt,name=txPower,proto3" json:"txPower,omitempty"`
	RadioMode         string                 `protobuf:"bytes,15,opt,name=radioMode,proto3" json:"radioMode,omitempty"`
	NoiseFloor        int32                  `protobuf:"varint,16,opt,name=noiseFloor,proto3" json:"noiseFloor,omitempty"`
	Latency           int32                  `protobuf:"varint,17,opt,name=latency,proto3" json:"latency,omitempty"`
	Capacity          uint32                 `protobuf:"varint,18,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Airtime           *AirtimeInfo           `protobuf:"bytes,21,opt,name=airtime,proto3" json:"airtime,omitempty"`
	Traffic           *ApTrafficInfo         `protobuf:"bytes,22,opt,name=traffic,proto3" json:"traffic,omitempty"`
	Wlan              []*WlanInfo            `protobuf:"bytes,23,rep,name=wlan,proto3" json:"wlan,omitempty"`
	IsCapacityFlagged bool                   `protobuf:"varint,31,opt,name=isCapacityFlagged,proto3" json:"isCapacityFlagged,omitempty"`
	IsLatencyFlagged  bool                   `protobuf:"varint,32,opt,name=isLatencyFlagged,proto3" json:"isLatencyFlagged,omitempty"`
	IsAirtimeFlagged  bool                   `protobuf:"varint,33,opt,name=isAirtimeFlagged,proto3" json:"isAirtimeFlagged,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RadioInfo) Reset() {
	*x = RadioInfo{}
	mi := &file_wnms_ap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadioInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadioInfo) ProtoMessage() {}

func (x *RadioInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_ap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadioInfo.ProtoReflect.Descriptor instead.
func (*RadioInfo) Descriptor() ([]byte, []int) {
	return file_wnms_ap_proto_rawDescGZIP(), []int{2}
}

func (x *RadioInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RadioInfo) GetClientNum() int32 {
	if x != nil {
		return x.ClientNum
	}
	return 0
}

func (x *RadioInfo) GetConnFailCnt() int32 {
	if x != nil {
		return x.ConnFailCnt
	}
	return 0
}

func (x *RadioInfo) GetFailureRate() float32 {
	if x != nil && x.FailureRate != nil {
		return *x.FailureRate
	}
	return 0
}

func (x *RadioInfo) GetMeshEnabled() int32 {
	if x != nil {
		return x.MeshEnabled
	}
	return 0
}

func (x *RadioInfo) GetIsRadioEnabled() bool {
	if x != nil {
		return x.IsRadioEnabled
	}
	return false
}

func (x *RadioInfo) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *RadioInfo) GetBand() string {
	if x != nil {
		return x.Band
	}
	return ""
}

func (x *RadioInfo) GetChannelWidth() uint32 {
	if x != nil {
		return x.ChannelWidth
	}
	return 0
}

func (x *RadioInfo) GetTxPower() string {
	if x != nil {
		return x.TxPower
	}
	return ""
}

func (x *RadioInfo) GetRadioMode() string {
	if x != nil {
		return x.RadioMode
	}
	return ""
}

func (x *RadioInfo) GetNoiseFloor() int32 {
	if x != nil {
		return x.NoiseFloor
	}
	return 0
}

func (x *RadioInfo) GetLatency() int32 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *RadioInfo) GetCapacity() uint32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *RadioInfo) GetAirtime() *AirtimeInfo {
	if x != nil {
		return x.Airtime
	}
	return nil
}

func (x *RadioInfo) GetTraffic() *ApTrafficInfo {
	if x != nil {
		return x.Traffic
	}
	return nil
}

func (x *RadioInfo) GetWlan() []*WlanInfo {
	if x != nil {
		return x.Wlan
	}
	return nil
}

func (x *RadioInfo) GetIsCapacityFlagged() bool {
	if x != nil {
		return x.IsCapacityFlagged
	}
	return false
}

func (x *RadioInfo) GetIsLatencyFlagged() bool {
	if x != nil {
		return x.IsLatencyFlagged
	}
	return false
}

func (x *RadioInfo) GetIsAirtimeFlagged() bool {
	if x != nil {
		return x.IsAirtimeFlagged
	}
	return false
}

type HardwareInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent     float32                `protobuf:"fixed32,1,opt,name=cpuPercent,proto3" json:"cpuPercent,omitempty"`
	StoragePercent float32                `protobuf:"fixed32,2,opt,name=storagePercent,proto3" json:"storagePercent,omitempty"`
	MemPercent     float32                `protobuf:"fixed32,3,opt,name=memPercent,proto3" json:"memPercent,omitempty"`
	Temperature    *float32               `protobuf:"fixed32,4,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HardwareInfo) Reset() {
	*x = HardwareInfo{}
	mi := &file_wnms_ap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareInfo) ProtoMessage() {}

func (x *HardwareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_ap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareInfo.ProtoReflect.Descriptor instead.
func (*HardwareInfo) Descriptor() ([]byte, []int) {
	return file_wnms_ap_proto_rawDescGZIP(), []int{3}
}

func (x *HardwareInfo) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *HardwareInfo) GetStoragePercent() float32 {
	if x != nil {
		return x.StoragePercent
	}
	return 0
}

func (x *HardwareInfo) GetMemPercent() float32 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *HardwareInfo) GetTemperature() float32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

type ApTrafficInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 부팅 이후 전체 총량
	RxBytes   int64 `protobuf:"varint,1,opt,name=rxBytes,proto3" json:"rxBytes,omitempty"`
	TxBytes   int64 `protobuf:"varint,2,opt,name=txBytes,proto3" json:"txBytes,omitempty"`
	RxPackets int64 `protobuf:"varint,3,opt,name=rxPackets,proto3" json:"rxPackets,omitempty"`
	TxPackets int64 `protobuf:"varint,4,opt,name=txPackets,proto3" json:"txPackets,omitempty"`
	// 마지막 전송 시점부터 현재 전송 시점까지의 통계 정보
	RxBytesDelta   int64 `protobuf:"varint,11,opt,name=rxBytesDelta,proto3" json:"rxBytesDelta,omitempty"`
	TxBytesDelta   int64 `protobuf:"varint,12,opt,name=txBytesDelta,proto3" json:"txBytesDelta,omitempty"`
	RxPacketsDelta int64 `protobuf:"varint,13,opt,name=rxPacketsDelta,proto3" json:"rxPacketsDelta,omitempty"`
	TxPacketsDelta int64 `protobuf:"varint,14,opt,name=txPacketsDelta,proto3" json:"txPacketsDelta,omitempty"`
	// 마지막 전송 시점부터 현재 전송 시점까지의 속도
	RxBps         int64 `protobuf:"varint,15,opt,name=rxBps,proto3" json:"rxBps,omitempty"`
	TxBps         int64 `protobuf:"varint,16,opt,name=txBps,proto3" json:"txBps,omitempty"`
	RxPps         int64 `protobuf:"varint,17,opt,name=rxPps,proto3" json:"rxPps,omitempty"`
	TxPps         int64 `protobuf:"varint,18,opt,name=txPps,proto3" json:"txPps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApTrafficInfo) Reset() {
	*x = ApTrafficInfo{}
	mi := &file_wnms_ap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApTrafficInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApTrafficInfo) ProtoMessage() {}

func (x *ApTrafficInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_ap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApTrafficInfo.ProtoReflect.Descriptor instead.
func (*ApTrafficInfo) Descriptor() ([]byte, []int) {
	return file_wnms_ap_proto_rawDescGZIP(), []int{4}
}

func (x *ApTrafficInfo) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *ApTrafficInfo) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *ApTrafficInfo) GetRxPackets() int64 {
	if x != nil {
		return x.RxPackets
	}
	return 0
}

func (x *ApTrafficInfo) GetTxPackets() int64 {
	if x != nil {
		return x.TxPackets
	}
	return 0
}

func (x *ApTrafficInfo) GetRxBytesDelta() int64 {
	if x != nil {
		return x.RxBytesDelta
	}
	return 0
}

func (x *ApTrafficInfo) GetTxBytesDelta() int64 {
	if x != nil {
		return x.TxBytesDelta
	}
	return 0
}

func (x *ApTrafficInfo) GetRxPacketsDelta() int64 {
	if x != nil {
		return x.RxPacketsDelta
	}
	return 0
}

func (x *ApTrafficInfo) GetTxPacketsDelta() int64 {
	if x != nil {
		return x.TxPacketsDelta
	}
	return 0
}

func (x *ApTrafficInfo) GetRxBps() int64 {
	if x != nil {
		return x.RxBps
	}
	return 0
}

func (x *ApTrafficInfo) GetTxBps() int64 {
	if x != nil {
		return x.TxBps
	}
	return 0
}

func (x *ApTrafficInfo) GetRxPps() int64 {
	if x != nil {
		return x.RxPps
	}
	return 0
}

func (x *ApTrafficInfo) GetTxPps() int64 {
	if x != nil {
		return x.TxPps
	}
	return 0
}

type AirtimeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtilRx        float32                `protobuf:"fixed32,1,opt,name=utilRx,proto3" json:"utilRx,omitempty"`
	UtilTx        float32                `protobuf:"fixed32,2,opt,name=utilTx,proto3" json:"utilTx,omitempty"`
	UtilBusy      float32                `protobuf:"fixed32,3,opt,name=utilBusy,proto3" json:"utilBusy,omitempty"`
	UtilTotal     float32                `protobuf:"fixed32,4,opt,name=utilTotal,proto3" json:"utilTotal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AirtimeInfo) Reset() {
	*x = AirtimeInfo{}
	mi := &file_wnms_ap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirtimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirtimeInfo) ProtoMessage() {}

func (x *AirtimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_ap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirtimeInfo.ProtoReflect.Descriptor instead.
func (*AirtimeInfo) Descriptor() ([]byte, []int) {
	return file_wnms_ap_proto_rawDescGZIP(), []int{5}
}

func (x *AirtimeInfo) GetUtilRx() float32 {
	if x != nil {
		return x.UtilRx
	}
	return 0
}

func (x *AirtimeInfo) GetUtilTx() float32 {
	if x != nil {
		return x.UtilTx
	}
	return 0
}

func (x *AirtimeInfo) GetUtilBusy() float32 {
	if x != nil {
		return x.UtilBusy
	}
	return 0
}

func (x *AirtimeInfo) GetUtilTotal() float32 {
	if x != nil {
		return x.UtilTotal
	}
	return 0
}

type WlanInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ssid           string                 `protobuf:"bytes,2,opt,name=ssid,proto3" json:"ssid,omitempty"`
	ClientNum      int32                  `protobuf:"varint,3,opt,name=clientNum,proto3" json:"clientNum,omitempty"`
	Enabled        bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Bssid          string                 `protobuf:"bytes,5,opt,name=bssid,proto3" json:"bssid,omitempty"`
	Radio80211Mode string                 `protobuf:"bytes,6,opt,name=radio80211Mode,proto3" json:"radio80211Mode,omitempty"`
	AuthMethod     string                 `protobuf:"bytes,7,opt,name=authMethod,proto3" json:"authMethod,omitempty"`
	EncMethod      string                 `protobuf:"bytes,8,opt,name=encMethod,proto3" json:"encMethod,omitempty"`
	RxBytesDelta   int64                  `protobuf:"varint,11,opt,name=rxBytesDelta,proto3" json:"rxBytesDelta,omitempty"`
	TxBytesDelta   int64                  `protobuf:"varint,12,opt,name=txBytesDelta,proto3" json:"txBytesDelta,omitempty"`
	RxPacketsDelta int64                  `protobuf:"varint,13,opt,name=rxPacketsDelta,proto3" json:"rxPacketsDelta,omitempty"`
	TxPacketsDelta int64                  `protobuf:"varint,14,opt,name=txPacketsDelta,proto3" json:"txPacketsDelta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WlanInfo) Reset() {
	*x = WlanInfo{}
	mi := &file_wnms_ap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WlanInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WlanInfo) ProtoMessage() {}

func (x *WlanInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_ap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WlanInfo.ProtoReflect.Descriptor instead.
func (*WlanInfo) Descriptor() ([]byte, []int) {
	return file_wnms_ap_proto_rawDescGZIP(), []int{6}
}

func (x *WlanInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WlanInfo) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *WlanInfo) GetClientNum() int32 {
	if x != nil {
		return x.ClientNum
	}
	return 0
}

func (x *WlanInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *WlanInfo) GetBssid() string {
	if x != nil {
		return x.Bssid
	}
	return ""
}

func (x *WlanInfo) GetRadio80211Mode() string {
	if x != nil {
		return x.Radio80211Mode
	}
	return ""
}

func (x *WlanInfo) GetAuthMethod() string {
	if x != nil {
		return x.AuthMethod
	}
	return ""
}

func (x *WlanInfo) GetEncMethod() string {
	if x != nil {
		return x.EncMethod
	}
	return ""
}

func (x *WlanInfo) GetRxBytesDelta() int64 {
	if x != nil {
		return x.RxBytesDelta
	}
	return 0
}

func (x *WlanInfo) GetTxBytesDelta() int64 {
	if x != nil {
		return x.TxBytesDelta
	}
	return 0
}

func (x *WlanInfo) GetRxPacketsDelta() int64 {
	if x != nil {
		return x.RxPacketsDelta
	}
	return 0
}

func (x *WlanInfo) GetTxPacketsDelta() int64 {
	if x != nil {
		return x.TxPacketsDelta
	}
	return 0
}

var File_wnms_ap_proto protoreflect.FileDescriptor

const file_wnms_ap_proto_rawDesc = "" +
	"\n" +
	"\rwnms_ap.proto\x12\x1fkr.connectlabs.wnms.proto.model\"\x7f\n" +
	"\bApReport\x12?\n" +
	"\x06apList\x18\x03 \x03(\v2'.kr.connectlabs.wnms.proto.model.ApInfoR\x06apList\x12\x14\n" +
	"\x05ApNum\x18\x04 \x01(\x05R\x05ApNum\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xbb\x04\n" +
	"\x06ApInfo\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\tR\x03mac\x12\x1c\n" +
	"\tipAddress\x18\x02 \x01(\tR\tipAddress\x12\"\n" +
	"\fserialNumber\x18\x03 \x01(\tR\fserialNumber\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\"\n" +
	"\fcontrollerIp\x18\x05 \x01(\tR\fcontrollerIp\x12\x12\n" +
	"\x04dpIp\x18\x06 \x01(\tR\x04dpIp\x12\x1e\n" +
	"\n" +
	"lastBootTs\x18\a \x01(\x04R\n" +
	"lastBootTs\x12\x18\n" +
	"\aapState\x18\b \x01(\tR\aapState\x12\x1c\n" +
	"\tclientNum\x18\t \x01(\x05R\tclientNum\x12\x16\n" +
	"\x06vendor\x18\n" +
	" \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\v \x01(\tR\x05model\x12=\n" +
	"\x02hw\x18\x15 \x01(\v2-.kr.connectlabs.wnms.proto.model.HardwareInfoR\x02hw\x12H\n" +
	"\atraffic\x18\x16 \x01(\v2..kr.connectlabs.wnms.proto.model.ApTrafficInfoR\atraffic\x12@\n" +
	"\x05radio\x18\x17 \x03(\v2*.kr.connectlabs.wnms.proto.model.RadioInfoR\x05radio\x12\x1e\n" +
	"\n" +
	"regionCode\x18[ \x01(\tR\n" +
	"regionCode\x12 \n" +
	"\vfactoryCode\x18\\ \x01(\tR\vfactoryCode\"\x9d\x06\n" +
	"\tRadioInfo\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1c\n" +
	"\tclientNum\x18\x02 \x01(\x05R\tclientNum\x12 \n" +
	"\vconnFailCnt\x18\x03 \x01(\x05R\vconnFailCnt\x12%\n" +
	"\vfailureRate\x18\x04 \x01(\x02H\x00R\vfailureRate\x88\x01\x01\x12 \n" +
	"\vmeshEnabled\x18\x05 \x01(\x05R\vmeshEnabled\x12&\n" +
	"\x0eisRadioEnabled\x18\x06 \x01(\bR\x0eisRadioEnabled\x12\x18\n" +
	"\achannel\x18\v \x01(\x05R\achannel\x12\x12\n" +
	"\x04band\x18\f \x01(\tR\x04band\x12\"\n" +
	"\fchannelWidth\x18\r \x01(\rR\fchannelWidth\x12\x18\n" +
	"\atxPower\x18\x0e \x01(\tR\atxPower\x12\x1c\n" +
	"\tradioMode\x18\x0f \x01(\tR\tradioMode\x12\x1e\n" +
	"\n" +
	"noiseFloor\x18\x10 \x01(\x05R\n" +
	"noiseFloor\x12\x18\n" +
	"\alatency\x18\x11 \x01(\x05R\alatency\x12\x1a\n" +
	"\bcapacity\x18\x12 \x01(\rR\bcapacity\x12F\n" +
	"\aairtime\x18\x15 \x01(\v2,.kr.connectlabs.wnms.proto.model.AirtimeInfoR\aairtime\x12H\n" +
	"\atraffic\x18\x16 \x01(\v2..kr.connectlabs.wnms.proto.model.ApTrafficInfoR\atraffic\x12=\n" +
	"\x04wlan\x18\x17 \x03(\v2).kr.connectlabs.wnms.proto.model.WlanInfoR\x04wlan\x12,\n" +
	"\x11isCapacityFlagged\x18\x1f \x01(\bR\x11isCapacityFlagged\x12*\n" +
	"\x10isLatencyFlagged\x18  \x01(\bR\x10isLatencyFlagged\x12*\n" +
	"\x10isAirtimeFlagged\x18! \x01(\bR\x10isAirtimeFlaggedB\x0e\n" +
	"\f_failureRate\"\xad\x01\n" +
	"\fHardwareInfo\x12\x1e\n" +
	"\n" +
	"cpuPercent\x18\x01 \x01(\x02R\n" +
	"cpuPercent\x12&\n" +
	"\x0estoragePercent\x18\x02 \x01(\x02R\x0estoragePercent\x12\x1e\n" +
	"\n" +
	"memPercent\x18\x03 \x01(\x02R\n" +
	"memPercent\x12%\n" +
	"\vtemperature\x18\x04 \x01(\x02H\x00R\vtemperature\x88\x01\x01B\x0e\n" +
	"\f_temperature\"\xef\x02\n" +
	"\rApTrafficInfo\x12\x18\n" +
	"\arxBytes\x18\x01 \x01(\x03R\arxBytes\x12\x18\n" +
	"\atxBytes\x18\x02 \x01(\x03R\atxBytes\x12\x1c\n" +
	"\trxPackets\x18\x03 \x01(\x03R\trxPackets\x12\x1c\n" +
	"\ttxPackets\x18\x04 \x01(\x03R\ttxPackets\x12\"\n" +
	"\frxBytesDelta\x18\v \x01(\x03R\frxBytesDelta\x12\"\n" +
	"\ftxBytesDelta\x18\f \x01(\x03R\ftxBytesDelta\x12&\n" +
	"\x0erxPacketsDelta\x18\r \x01(\x03R\x0erxPacketsDelta\x12&\n" +
	"\x0etxPacketsDelta\x18\x0e \x01(\x03R\x0etxPacketsDelta\x12\x14\n" +
	"\x05rxBps\x18\x0f \x01(\x03R\x05rxBps\x12\x14\n" +
	"\x05txBps\x18\x10 \x01(\x03R\x05txBps\x12\x14\n" +
	"\x05rxPps\x18\x11 \x01(\x03R\x05rxPps\x12\x14\n" +
	"\x05txPps\x18\x12 \x01(\x03R\x05txPps\"w\n" +
	"\vAirtimeInfo\x12\x16\n" +
	"\x06utilRx\x18\x01 \x01(\x02R\x06utilRx\x12\x16\n" +
	"\x06utilTx\x18\x02 \x01(\x02R\x06utilTx\x12\x1a\n" +
	"\butilBusy\x18\x03 \x01(\x02R\butilBusy\x12\x1c\n" +
	"\tutilTotal\x18\x04 \x01(\x02R\tutilTotal\"\xfe\x02\n" +
	"\bWlanInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04ssid\x18\x02 \x01(\tR\x04ssid\x12\x1c\n" +
	"\tclientNum\x18\x03 \x01(\x05R\tclientNum\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x14\n" +
	"\x05bssid\x18\x05 \x01(\tR\x05bssid\x12&\n" +
	"\x0eradio80211Mode\x18\x06 \x01(\tR\x0eradio80211Mode\x12\x1e\n" +
	"\n" +
	"authMethod\x18\a \x01(\tR\n" +
	"authMethod\x12\x1c\n" +
	"\tencMethod\x18\b \x01(\tR\tencMethod\x12\"\n" +
	"\frxBytesDelta\x18\v \x01(\x03R\frxBytesDelta\x12\"\n" +
	"\ftxBytesDelta\x18\f \x01(\x03R\ftxBytesDelta\x12&\n" +
	"\x0erxPacketsDelta\x18\r \x01(\x03R\x0erxPacketsDelta\x12&\n" +
	"\x0etxPacketsDelta\x18\x0e \x01(\x03R\x0etxPacketsDeltaB\n" +
	"Z\b../modelb\x06proto3"

var (
	file_wnms_ap_proto_rawDescOnce sync.Once
	file_wnms_ap_proto_rawDescData []byte
)

func file_wnms_ap_proto_rawDescGZIP() []byte {
	file_wnms_ap_proto_rawDescOnce.Do(func() {
		file_wnms_ap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wnms_ap_proto_rawDesc), len(file_wnms_ap_proto_rawDesc)))
	})
	return file_wnms_ap_proto_rawDescData
}

var file_wnms_ap_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_wnms_ap_proto_goTypes = []any{
	(*ApReport)(nil),      // 0: kr.connectlabs.wnms.proto.model.ApReport
	(*ApInfo)(nil),        // 1: kr.connectlabs.wnms.proto.model.ApInfo
	(*RadioInfo)(nil),     // 2: kr.connectlabs.wnms.proto.model.RadioInfo
	(*HardwareInfo)(nil),  // 3: kr.connectlabs.wnms.proto.model.HardwareInfo
	(*ApTrafficInfo)(nil), // 4: kr.connectlabs.wnms.proto.model.ApTrafficInfo
	(*AirtimeInfo)(nil),   // 5: kr.connectlabs.wnms.proto.model.AirtimeInfo
	(*WlanInfo)(nil),      // 6: kr.connectlabs.wnms.proto.model.WlanInfo
}
var file_wnms_ap_proto_depIdxs = []int32{
	1, // 0: kr.connectlabs.wnms.proto.model.ApReport.apList:type_name -> kr.connectlabs.wnms.proto.model.ApInfo
	3, // 1: kr.connectlabs.wnms.proto.model.ApInfo.hw:type_name -> kr.connectlabs.wnms.proto.model.HardwareInfo
	4, // 2: kr.connectlabs.wnms.proto.model.ApInfo.traffic:type_name -> kr.connectlabs.wnms.proto.model.ApTrafficInfo
	2, // 3: kr.connectlabs.wnms.proto.model.ApInfo.radio:type_name -> kr.connectlabs.wnms.proto.model.RadioInfo
	5, // 4: kr.connectlabs.wnms.proto.model.RadioInfo.airtime:type_name -> kr.connectlabs.wnms.proto.model.AirtimeInfo
	4, // 5: kr.connectlabs.wnms.proto.model.RadioInfo.traffic:type_name -> kr.connectlabs.wnms.proto.model.ApTrafficInfo
	6, // 6: kr.connectlabs.wnms.proto.model.RadioInfo.wlan:type_name -> kr.connectlabs.wnms.proto.model.WlanInfo
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_wnms_ap_proto_init() }
func file_wnms_ap_proto_init() {
	if File_wnms_ap_proto != nil {
		return
	}
	file_wnms_ap_proto_msgTypes[2].OneofWrappers = []any{}
	file_wnms_ap_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wnms_ap_proto_rawDesc), len(file_wnms_ap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wnms_ap_proto_goTypes,
		DependencyIndexes: file_wnms_ap_proto_depIdxs,
		MessageInfos:      file_wnms_ap_proto_msgTypes,
	}.Build()
	File_wnms_ap_proto = out.File
	file_wnms_ap_proto_goTypes = nil
	file_wnms_ap_proto_depIdxs = nil
}
