// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: wnms_statistics.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatisticsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statistics    *Statistics            `protobuf:"bytes,1,opt,name=statistics,proto3" json:"statistics,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsReport) Reset() {
	*x = StatisticsReport{}
	mi := &file_wnms_statistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsReport) ProtoMessage() {}

func (x *StatisticsReport) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_statistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsReport.ProtoReflect.Descriptor instead.
func (*StatisticsReport) Descriptor() ([]byte, []int) {
	return file_wnms_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *StatisticsReport) GetStatistics() *Statistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

func (x *StatisticsReport) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Statistics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CurrentWiFiAlarmCnt int32                  `protobuf:"varint,11,opt,name=currentWiFiAlarmCnt,proto3" json:"currentWiFiAlarmCnt,omitempty"`
	CurrentWiFiEventCnt int32                  `protobuf:"varint,12,opt,name=currentWiFiEventCnt,proto3" json:"currentWiFiEventCnt,omitempty"`
	AlarmStatusMap      map[string]string      `protobuf:"bytes,13,rep,name=alarmStatusMap,proto3" json:"alarmStatusMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RegionCode          string                 `protobuf:"bytes,91,opt,name=regionCode,proto3" json:"regionCode,omitempty"`
	FactoryCode         string                 `protobuf:"bytes,92,opt,name=factoryCode,proto3" json:"factoryCode,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Statistics) Reset() {
	*x = Statistics{}
	mi := &file_wnms_statistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistics) ProtoMessage() {}

func (x *Statistics) ProtoReflect() protoreflect.Message {
	mi := &file_wnms_statistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistics.ProtoReflect.Descriptor instead.
func (*Statistics) Descriptor() ([]byte, []int) {
	return file_wnms_statistics_proto_rawDescGZIP(), []int{1}
}

func (x *Statistics) GetCurrentWiFiAlarmCnt() int32 {
	if x != nil {
		return x.CurrentWiFiAlarmCnt
	}
	return 0
}

func (x *Statistics) GetCurrentWiFiEventCnt() int32 {
	if x != nil {
		return x.CurrentWiFiEventCnt
	}
	return 0
}

func (x *Statistics) GetAlarmStatusMap() map[string]string {
	if x != nil {
		return x.AlarmStatusMap
	}
	return nil
}

func (x *Statistics) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

func (x *Statistics) GetFactoryCode() string {
	if x != nil {
		return x.FactoryCode
	}
	return ""
}

var File_wnms_statistics_proto protoreflect.FileDescriptor

const file_wnms_statistics_proto_rawDesc = "" +
	"\n" +
	"\x15wnms_statistics.proto\x12\x1fkr.connectlabs.wnms.proto.model\"}\n" +
	"\x10StatisticsReport\x12K\n" +
	"\n" +
	"statistics\x18\x01 \x01(\v2+.kr.connectlabs.wnms.proto.model.StatisticsR\n" +
	"statistics\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\"\xde\x02\n" +
	"\n" +
	"Statistics\x120\n" +
	"\x13currentWiFiAlarmCnt\x18\v \x01(\x05R\x13currentWiFiAlarmCnt\x120\n" +
	"\x13currentWiFiEventCnt\x18\f \x01(\x05R\x13currentWiFiEventCnt\x12g\n" +
	"\x0ealarmStatusMap\x18\r \x03(\v2?.kr.connectlabs.wnms.proto.model.Statistics.AlarmStatusMapEntryR\x0ealarmStatusMap\x12\x1e\n" +
	"\n" +
	"regionCode\x18[ \x01(\tR\n" +
	"regionCode\x12 \n" +
	"\vfactoryCode\x18\\ \x01(\tR\vfactoryCode\x1aA\n" +
	"\x13AlarmStatusMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"Z\b../modelb\x06proto3"

var (
	file_wnms_statistics_proto_rawDescOnce sync.Once
	file_wnms_statistics_proto_rawDescData []byte
)

func file_wnms_statistics_proto_rawDescGZIP() []byte {
	file_wnms_statistics_proto_rawDescOnce.Do(func() {
		file_wnms_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wnms_statistics_proto_rawDesc), len(file_wnms_statistics_proto_rawDesc)))
	})
	return file_wnms_statistics_proto_rawDescData
}

var file_wnms_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wnms_statistics_proto_goTypes = []any{
	(*StatisticsReport)(nil), // 0: kr.connectlabs.wnms.proto.model.StatisticsReport
	(*Statistics)(nil),       // 1: kr.connectlabs.wnms.proto.model.Statistics
	nil,                      // 2: kr.connectlabs.wnms.proto.model.Statistics.AlarmStatusMapEntry
}
var file_wnms_statistics_proto_depIdxs = []int32{
	1, // 0: kr.connectlabs.wnms.proto.model.StatisticsReport.statistics:type_name -> kr.connectlabs.wnms.proto.model.Statistics
	2, // 1: kr.connectlabs.wnms.proto.model.Statistics.alarmStatusMap:type_name -> kr.connectlabs.wnms.proto.model.Statistics.AlarmStatusMapEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wnms_statistics_proto_init() }
func file_wnms_statistics_proto_init() {
	if File_wnms_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wnms_statistics_proto_rawDesc), len(file_wnms_statistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wnms_statistics_proto_goTypes,
		DependencyIndexes: file_wnms_statistics_proto_depIdxs,
		MessageInfos:      file_wnms_statistics_proto_msgTypes,
	}.Build()
	File_wnms_statistics_proto = out.File
	file_wnms_statistics_proto_goTypes = nil
	file_wnms_statistics_proto_depIdxs = nil
}
