// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: wnms_collector_service.proto

package model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WnmsDataCollector_UpdateAccessPointData_FullMethodName = "/kr.connectlabs.wnms.proto.model.WnmsDataCollector/UpdateAccessPointData"
	WnmsDataCollector_UpdateClientData_FullMethodName      = "/kr.connectlabs.wnms.proto.model.WnmsDataCollector/UpdateClientData"
	WnmsDataCollector_UpdateEventData_FullMethodName       = "/kr.connectlabs.wnms.proto.model.WnmsDataCollector/UpdateEventData"
	WnmsDataCollector_UpdateAlarmData_FullMethodName       = "/kr.connectlabs.wnms.proto.model.WnmsDataCollector/UpdateAlarmData"
	WnmsDataCollector_UpdateConfigData_FullMethodName      = "/kr.connectlabs.wnms.proto.model.WnmsDataCollector/UpdateConfigData"
	WnmsDataCollector_UpdatePlaneData_FullMethodName       = "/kr.connectlabs.wnms.proto.model.WnmsDataCollector/UpdatePlaneData"
	WnmsDataCollector_PingData_FullMethodName              = "/kr.connectlabs.wnms.proto.model.WnmsDataCollector/PingData"
	WnmsDataCollector_UpdateP5GStatsData_FullMethodName    = "/kr.connectlabs.wnms.proto.model.WnmsDataCollector/UpdateP5gStatsData"
	WnmsDataCollector_UpdateP5GUeStatsData_FullMethodName  = "/kr.connectlabs.wnms.proto.model.WnmsDataCollector/UpdateP5gUeStatsData"
	WnmsDataCollector_UpdateStatisticsData_FullMethodName  = "/kr.connectlabs.wnms.proto.model.WnmsDataCollector/UpdateStatisticsData"
)

// WnmsDataCollectorClient is the client API for WnmsDataCollector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WnmsDataCollectorClient interface {
	UpdateAccessPointData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error)
	UpdateClientData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error)
	UpdateEventData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error)
	UpdateAlarmData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error)
	UpdateConfigData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error)
	UpdatePlaneData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error)
	PingData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error)
	UpdateP5GStatsData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error)
	UpdateP5GUeStatsData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error)
	UpdateStatisticsData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error)
}

type wnmsDataCollectorClient struct {
	cc grpc.ClientConnInterface
}

func NewWnmsDataCollectorClient(cc grpc.ClientConnInterface) WnmsDataCollectorClient {
	return &wnmsDataCollectorClient{cc}
}

func (c *wnmsDataCollectorClient) UpdateAccessPointData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, WnmsDataCollector_UpdateAccessPointData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wnmsDataCollectorClient) UpdateClientData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, WnmsDataCollector_UpdateClientData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wnmsDataCollectorClient) UpdateEventData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, WnmsDataCollector_UpdateEventData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wnmsDataCollectorClient) UpdateAlarmData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, WnmsDataCollector_UpdateAlarmData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wnmsDataCollectorClient) UpdateConfigData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, WnmsDataCollector_UpdateConfigData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wnmsDataCollectorClient) UpdatePlaneData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, WnmsDataCollector_UpdatePlaneData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wnmsDataCollectorClient) PingData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, WnmsDataCollector_PingData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wnmsDataCollectorClient) UpdateP5GStatsData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, WnmsDataCollector_UpdateP5GStatsData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wnmsDataCollectorClient) UpdateP5GUeStatsData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, WnmsDataCollector_UpdateP5GUeStatsData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wnmsDataCollectorClient) UpdateStatisticsData(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcReply)
	err := c.cc.Invoke(ctx, WnmsDataCollector_UpdateStatisticsData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WnmsDataCollectorServer is the server API for WnmsDataCollector service.
// All implementations must embed UnimplementedWnmsDataCollectorServer
// for forward compatibility.
type WnmsDataCollectorServer interface {
	UpdateAccessPointData(context.Context, *RpcRequest) (*RpcReply, error)
	UpdateClientData(context.Context, *RpcRequest) (*RpcReply, error)
	UpdateEventData(context.Context, *RpcRequest) (*RpcReply, error)
	UpdateAlarmData(context.Context, *RpcRequest) (*RpcReply, error)
	UpdateConfigData(context.Context, *RpcRequest) (*RpcReply, error)
	UpdatePlaneData(context.Context, *RpcRequest) (*RpcReply, error)
	PingData(context.Context, *RpcRequest) (*RpcReply, error)
	UpdateP5GStatsData(context.Context, *RpcRequest) (*RpcReply, error)
	UpdateP5GUeStatsData(context.Context, *RpcRequest) (*RpcReply, error)
	UpdateStatisticsData(context.Context, *RpcRequest) (*RpcReply, error)
	mustEmbedUnimplementedWnmsDataCollectorServer()
}

// UnimplementedWnmsDataCollectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWnmsDataCollectorServer struct{}

func (UnimplementedWnmsDataCollectorServer) UpdateAccessPointData(context.Context, *RpcRequest) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccessPointData not implemented")
}
func (UnimplementedWnmsDataCollectorServer) UpdateClientData(context.Context, *RpcRequest) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClientData not implemented")
}
func (UnimplementedWnmsDataCollectorServer) UpdateEventData(context.Context, *RpcRequest) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEventData not implemented")
}
func (UnimplementedWnmsDataCollectorServer) UpdateAlarmData(context.Context, *RpcRequest) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAlarmData not implemented")
}
func (UnimplementedWnmsDataCollectorServer) UpdateConfigData(context.Context, *RpcRequest) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfigData not implemented")
}
func (UnimplementedWnmsDataCollectorServer) UpdatePlaneData(context.Context, *RpcRequest) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlaneData not implemented")
}
func (UnimplementedWnmsDataCollectorServer) PingData(context.Context, *RpcRequest) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingData not implemented")
}
func (UnimplementedWnmsDataCollectorServer) UpdateP5GStatsData(context.Context, *RpcRequest) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateP5GStatsData not implemented")
}
func (UnimplementedWnmsDataCollectorServer) UpdateP5GUeStatsData(context.Context, *RpcRequest) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateP5GUeStatsData not implemented")
}
func (UnimplementedWnmsDataCollectorServer) UpdateStatisticsData(context.Context, *RpcRequest) (*RpcReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatisticsData not implemented")
}
func (UnimplementedWnmsDataCollectorServer) mustEmbedUnimplementedWnmsDataCollectorServer() {}
func (UnimplementedWnmsDataCollectorServer) testEmbeddedByValue()                           {}

// UnsafeWnmsDataCollectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WnmsDataCollectorServer will
// result in compilation errors.
type UnsafeWnmsDataCollectorServer interface {
	mustEmbedUnimplementedWnmsDataCollectorServer()
}

func RegisterWnmsDataCollectorServer(s grpc.ServiceRegistrar, srv WnmsDataCollectorServer) {
	// If the following call pancis, it indicates UnimplementedWnmsDataCollectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WnmsDataCollector_ServiceDesc, srv)
}

func _WnmsDataCollector_UpdateAccessPointData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WnmsDataCollectorServer).UpdateAccessPointData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WnmsDataCollector_UpdateAccessPointData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WnmsDataCollectorServer).UpdateAccessPointData(ctx, req.(*RpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WnmsDataCollector_UpdateClientData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WnmsDataCollectorServer).UpdateClientData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WnmsDataCollector_UpdateClientData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WnmsDataCollectorServer).UpdateClientData(ctx, req.(*RpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WnmsDataCollector_UpdateEventData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WnmsDataCollectorServer).UpdateEventData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WnmsDataCollector_UpdateEventData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WnmsDataCollectorServer).UpdateEventData(ctx, req.(*RpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WnmsDataCollector_UpdateAlarmData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WnmsDataCollectorServer).UpdateAlarmData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WnmsDataCollector_UpdateAlarmData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WnmsDataCollectorServer).UpdateAlarmData(ctx, req.(*RpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WnmsDataCollector_UpdateConfigData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WnmsDataCollectorServer).UpdateConfigData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WnmsDataCollector_UpdateConfigData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WnmsDataCollectorServer).UpdateConfigData(ctx, req.(*RpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WnmsDataCollector_UpdatePlaneData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WnmsDataCollectorServer).UpdatePlaneData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WnmsDataCollector_UpdatePlaneData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WnmsDataCollectorServer).UpdatePlaneData(ctx, req.(*RpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WnmsDataCollector_PingData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WnmsDataCollectorServer).PingData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WnmsDataCollector_PingData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WnmsDataCollectorServer).PingData(ctx, req.(*RpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WnmsDataCollector_UpdateP5GStatsData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WnmsDataCollectorServer).UpdateP5GStatsData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WnmsDataCollector_UpdateP5GStatsData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WnmsDataCollectorServer).UpdateP5GStatsData(ctx, req.(*RpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WnmsDataCollector_UpdateP5GUeStatsData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WnmsDataCollectorServer).UpdateP5GUeStatsData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WnmsDataCollector_UpdateP5GUeStatsData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WnmsDataCollectorServer).UpdateP5GUeStatsData(ctx, req.(*RpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WnmsDataCollector_UpdateStatisticsData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WnmsDataCollectorServer).UpdateStatisticsData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WnmsDataCollector_UpdateStatisticsData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WnmsDataCollectorServer).UpdateStatisticsData(ctx, req.(*RpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WnmsDataCollector_ServiceDesc is the grpc.ServiceDesc for WnmsDataCollector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WnmsDataCollector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kr.connectlabs.wnms.proto.model.WnmsDataCollector",
	HandlerType: (*WnmsDataCollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateAccessPointData",
			Handler:    _WnmsDataCollector_UpdateAccessPointData_Handler,
		},
		{
			MethodName: "UpdateClientData",
			Handler:    _WnmsDataCollector_UpdateClientData_Handler,
		},
		{
			MethodName: "UpdateEventData",
			Handler:    _WnmsDataCollector_UpdateEventData_Handler,
		},
		{
			MethodName: "UpdateAlarmData",
			Handler:    _WnmsDataCollector_UpdateAlarmData_Handler,
		},
		{
			MethodName: "UpdateConfigData",
			Handler:    _WnmsDataCollector_UpdateConfigData_Handler,
		},
		{
			MethodName: "UpdatePlaneData",
			Handler:    _WnmsDataCollector_UpdatePlaneData_Handler,
		},
		{
			MethodName: "PingData",
			Handler:    _WnmsDataCollector_PingData_Handler,
		},
		{
			MethodName: "UpdateP5gStatsData",
			Handler:    _WnmsDataCollector_UpdateP5GStatsData_Handler,
		},
		{
			MethodName: "UpdateP5gUeStatsData",
			Handler:    _WnmsDataCollector_UpdateP5GUeStatsData_Handler,
		},
		{
			MethodName: "UpdateStatisticsData",
			Handler:    _WnmsDataCollector_UpdateStatisticsData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wnms_collector_service.proto",
}
